### ISSUE TITLE
Hydra Sphere adapter mesh doesn't align with origin

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1086]
### Description of Issue
The mesh representation used by Hydra to describe a sphere primitive does not align its points with the origin. I'd submit a pull request for this, but I was hoping that you have some sort of script for generatig the mesh description code automatically?

### Steps to Reproduce
1. Open a USD file with a default sphere primitive in usdview.
2. It's easiest to see in "points" drawing mode that the points don't align as one would expect with the axes.
3. Looking at the code, you can see there are nowhere near enough "0.0000" entries in the mesh (attached image shows both usdview and highlights all zero entries in the code).
![SphereMeshOffset](https://user-images.githubusercontent.com/1513015/72268089-2efcd980-35ef-11ea-9d1c-64ce8ec7acc5.png)

### Package Versions
19.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-5791

**Comment by c64kernal** [comment]
Thanks for reporting this @marktucker -- actually while doing the work in commit 5ed25d9fea53dc69c664eeee4a288a2d2fa061b9 this issue was also noticed. While the well intentioned engineer wanted to fix it on the spot, it was going to be too time consuming because many of our tests have baked in the assumptions about this incorrect positioning (he also pointed out that they're not spherical either :)). At any rate, this is definitely something we want to fix, but we will have to take the time to go through all our internal tests and update the bad assumptions in them before we can do that unfortunately.
