### ISSUE TITLE
[usdGenSchema] Header guard for schemaClass.h should have corresponding #endif in same file rather than being encoded in usdGenSchema.py logic

### ISSUE THREAD

**Issue by moddyz** [PixarAnimationStudios/USD#1092]
### Description of Issue

The `#ifndef ... #define` header guard started in [codegenTemplates/schemaClass.h](https://github.com/PixarAnimationStudios/USD/blob/v20.02-rc1/pxr/usd/usd/codegenTemplates/schemaClass.h#L24) should have a corresponding `#endif` at the end of the same file.  Currently, that `#endif` is added by [usdGenSchema.py](https://github.com/PixarAnimationStudios/USD/blob/v20.02-rc1/pxr/usd/usd/usdGenSchema.py#L932).

The use case is we prefer using `#pragma once` as the header guarding mechanism throughout our codebase.  It would be useful to be able to make this customisation purely through `codegenTemplates`.

### System Information (OS, Hardware)
ubuntu-18.04

### Package Versions
usd-19.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-5806

**Comment by spiffmon** [comment]
Hi @moddyz !
   Moving the "terminator" logic entirely out of usdGenSchema and into schemaClass.h templates would require the addition of a new line/token to robustly bracket the custom section... and I think you might also lose the ability to add free functions. But most importantly, the implication is that it would cause a diff to every single generated schema header, which is a pretty high overhead to accommodate this need.
   However, we would support a PR that adds a command-line option to usdGenSchema , --headerTerminatorString so that you are not stuck with the hardcoded string that's in there, now, when generating your local schemas.  You may want to add a companion argument that customizes the message that accompanies the ` --(BEGIN CUSTOM CODE)--` so that your users aren't still admonished to "Close the include guard with #endif"

**Comment by moddyz** [comment]
@spiffmon sounds like a solid plan 👍
