### ISSUE TITLE
building USD as static library

### ISSUE THREAD

**Issue by mistafunk** [PixarAnimationStudios/USD#12]
is there any chance to build USD as a static library?

**Comment by amooty** [comment]
Filed as internal issue #135165.

**Comment by c64kernal** [comment]
Unfortunately we don't have support to build USD as a static library at the moment.  Unfortunately, it's not clear if just building it out of the box as a static library will work at all.  We rely on a few platform-specific constructs that may add difficulty to building as a static library (e.g., you can track down the code starting with tf/registryManager.cpp).

**Comment by meshula** [comment]
I attempted this, and made it work.

The only issue is the registry managers. The trick to make it work when statically linked is everywhere TF_REGISTRY_FUNCTION is used, MFB_ALT_PACKAGE_NAME has to be set uniquely to emulate what it would be set as when built as so's.

To pull that off, the TF_REGISTRY_LOAD_MARKER instantiation has to be removed from tf/registryManager.h, and then relocated to all the places it would normally be used. For example, usdaFileFormat.cpp would become the file below. 

I didn't encounter any other issues besides this. This modification is rather intrusive, and touches roughly 150 source files. I'd suggest thinking of some other way to pull this off that is not quite so brute force.

#define MFB_ALT_PACKAGE_NAME usd
    #include "pxr/usd/usd/usdaFileFormat.h"

    #include "pxr/usd/usd/usdFileFormat.h"

    #include "pxr/usd/sdf/layer.h"
    #include "pxr/base/tf/registryManager.h"

    TF_REGISTRY_LOAD_MARKER;

    TF_DEFINE_PUBLIC_TOKENS(UsdUsdaFileFormatTokens, USD_USDA_FILE_FORMAT_TOKENS);

    TF_REGISTRY_FUNCTION(TfType)
    {
        SDF_DEFINE_FILE_FORMAT(UsdUsdaFileFormat, SdfTextFileFormat);
    }

    UsdUsdaFileFormat::UsdUsdaFileFormat()
        : SdfTextFileFormat(UsdUsdaFileFormatTokens->Id,
                            UsdUsdaFileFormatTokens->Version,
                            UsdUsdFileFormatTokens->Target)
    {
        // Do Nothing.
    }

    UsdUsdaFileFormat::~UsdUsdaFileFormat()
    {
        // Do Nothing.
    }

**Comment by meshula** [comment]
One more issue ~ Hydra imaging uses the address of the plugin so to get the Resources folder to find its shaders. There's probably a better way for glslfx files to be found that is not dependent on being loaded in an dynamic library. Perhaps we could enter that as an issue as well.

At the heart of the issue is this routine, and ArchGetAddressInfo - both GetPluginWithAddress, and ArchGetAddressInfo thwart general static linking. AFAICT the only non trivial use of them is Hydra finding its shaders. I'd recommend removing these two routines completely to avoid new dependencies on dynamic loading.

PlugPluginPtr
PlugPlugin::_GetPluginWithAddress(void* address)
{
    std::string path;
    return ArchGetAddressInfo(address, &path, NULL, NULL, NULL)
           ? _GetPluginWithPath(path)
           : TfNullPtr;
}

**Comment by sunyab** [comment]
Version 0.7.6 has added support for building USD as static libraries or a single monolithic shared library. Please have a look at the documentation in [BUILDING.md](https://github.com/PixarAnimationStudios/USD/blob/master/BUILDING.md#linker-options) for the various options that are provided.
