### ISSUE TITLE
GetExternalReferences and UpdateExternalReferences ignore value clips

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1264]
### Description of Issue
The GextExternalReferences and UpdateExternalReferences APIs don't pay any attention to value clips. I have a need to treat value clip files the same way as sublayers/references/payloads, and so I need to create versions of these methods that incorporate the value clip information. I'll be copy/pasting these existing functions to create new functions with this additional functionality. I can either:
1. Leave these functions outside USD if you don't think they are generally useful
2. Make a pull request to incorporate these new functions into USD with new names
3. Make a pull request that incorporates this functionality into the existing methods, either optionally or always

I'm also ignoring the UsdUtilsExtractExternalReferences method in this discussion. I don't particularly need that method, but if you go with option 3 it might make sense to include this method in the discussion as well?

**Comment by marktucker** [comment]
Nevermind. Turns out not to be the core of the problem I'm dealing with, and the more I think about it, the more I think clip files should be handled like other SdfAssetPath attributes/metadata, rather than dealing with them like payloads/references/sublayers.

**Comment by spiffmon** [comment]
It might make sense to keep this closed, but as I was investigating, I noticed some disturbing things...
1. First, as you are aware, those two SdfLayer functions **only** process composition arcs, though neither their names nor documentation really specify that.  The UsdUtils functions handle **all** external references, which is much more useful.  @sunyab suspects those functions may have predated general asset-valued attributes and metadata!
2. UpdateExternalReference() is broken - if a layer both sublayers and references the same external layer (which is completely legit), the references won't be updated.

We can see that the Solaris bridge uses these functions, so at minimum we should fix what is broken, or deprecate the functions altogether in favor of Usd-level or UsdUtils-level functionality... the other thing that is a bit concerning is that it's unclear exactly how to update clip template metadata in these scenarios?

Btw, 20.08 now has [ComputeClipAssetPaths](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/usd/clipsAPI.h#L237-L247) so that you don't need to replicate logic for expanding clip templates, though it operates on prims, not layers.

**Comment by marktucker** [comment]
Yeah, we rely on those functions in some very important areas of the code. I haven't seen them fail, but maybe we just haven't seen the specific arrangement of composition you're referring to. We do have our own code for traversing a layer and updating any SdfAssetPaths it finds in attributes or metadata because we know UpdateExternalReferences doesn't provide that capability.

Another related problem (at least related in my mind) is that I believe UsdFlattenLayerStack doesn't call the resolveAssetPathFn for clip metadata (and I assume the same is true for any SdfAssetPaths in metadata). I haven't tracked the code carefully to verify this, but setting debugger breakpoints tells me that it's missing these. I believe this is the real source of the problem that I was trying to pin on UpdateExternalReferences.

If I have pinned the problem on the right area of the code this time, would you be interested in a PR to fix this issue with UsdFlattenLayerStack?

**Comment by spiffmon** [comment]
> If I have pinned the problem on the right area of the code this time, would you be interested in a PR to fix this issue with UsdFlattenLayerStack?

Definitely!

Thanks, @marktucker !

**Comment by marktucker** [comment]
Cool. I can also look at migrating our use of the GetExternalReferences/UpdateExternalReferences functions to UsdUtilsModifyAssetPaths, if it's safer/better?

**Comment by spiffmon** [comment]
Yes, that might be a good idea - UsdUtilsModifyAssetPaths() is a function we actually _can_ make work properly for clips, when we decide what that is (and for non-template clips it will already do the right thing).

**Comment by marktucker** [comment]
FYI, Houdini 18.5 has been updated to eliminate all use of UpdateExternalReferences, though we do still use GetExternalReferences in a couple of places where it is actually doing what we want (when we really just want the references, payloads, and sublayers all returned in a single set). So no need to fix any bugs in that code on our account.

But it would be helpful to have the GetExternalReferences and UpdateExternalReferences documentation mention their limitations and point to the UsdUtils replacements.

Thanks for the guidance here!
