### ISSUE TITLE
GPU leaks when UsdImagingGLEngine::colorCorrectionMode = HdxColorCorrectionTokens->disabled

### ISSUE THREAD

**Issue by marsupial** [PixarAnimationStudios/USD#1286]
### Description of Issue
Running an instance of **UsdImagingGLEngine** with **UsdImagingGLEngine::colorCorrectionMode  = HdxColorCorrectionTokens->disabled** is leaking GPU resources.  I think the issue is really in Hdx, or Hgi, but very hard to track down what/where the leak is ocuring so far.

### Steps to Reproduce
1. Launch **usdview**, disable color correction.
2. Select a delegate _**other than Storm**_ (Prman is fine)
3. tumble the viewport causing refresh.
4. Watch GPU memory grow endlessly.

Doing the same with sRGB, or OCIO and the GPU memory will top out at some point. 

### System Information (OS, Hardware)
Tested on AMD & NVidia hardware

### Package Versions
dev, 20.08, (possibly 20.05)

**Comment by lumonix** [comment]
Hi @marsupial,

I recently fixed a bug that might be related.
If you want to try it, try putting 'static' in front of each of the vectors:

https://github.com/PixarAnimationStudios/USD/blob/release/pxr/imaging/hgiGL/garbageCollector.h#L87

I'll try to see if we can get this submitted to dev branch.

The memory leak happens when 'Hgi' is re-created (e.g. by using 'open' in usdview file menu) and then each time the viewport textures are updated some memory is leaked. If you run Renderman or Embree, it leaks very quickly, with Storm I think it only leaks when you resize the view.

**Comment by marsupial** [comment]
Sadly making those static doesn't change this leak.

**Comment by lumonix** [comment]
Ok thanks for trying that out.
I'm not able to reproduce any memory leak in our internal tree so far.

**Comment by marsupial** [comment]
Just to clarify in case it wasn't clear: this is **GPU** memory, not **CPU** memory, and effects delegates _other_ than Storm.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6280

**Comment by lumonix** [comment]
Hi @marsupial 

This issue was assigned to me, but I've been unable to reproduce this on our Linux machines.
I'm using 'watch nvidia-smi' to monitor the GPU memory.

NVIDIA-SMI 440.59	  Driver Version: 440.59

My steps are:

1. Open USDZ asset that has some meshes, textures and previewSurface materials in UsdView.
2. Run 'watch nvidia-smi' in another terminal.
3. Switch Color Management to 'Disabled' in UsdView.
4. Spin the viewport for a while.

GPU memory is stable.

Can you refine your repro?

**Comment by marsupial** [comment]
This isn't related to textures, but the full-frame blit of the display-aov from delegates **other than Storm**.

I can load up a simple no-texture, no-material cube, and as I navigate the viewport with _color-management disabled_ with **Embree**, **PrMan**, or any other delegate the second column of memory usage from `watch nvidia-smi` will grow ever increasing until the system warns me that GPU memory is being exhausted.

This doesn't happen with _OCIO_ or _sRGB_, and moving off _disabled_ to one of those and navigating some more, I can watch the memory fall.

**Comment by lumonix** [comment]
Got it thanks!
I found a repro internally too.

Garbage collection (for HgiGL) is supposed to run once at the end of the render frame (Hgi::EndFrame).
But we have been delaying adding Hgi::EndFrame calls into our code base while we wait for some other refactors.
So in the mean time, garbage collection run during HgiGL::_SubmitCmds.
If you have no tasks running (disabled color correction) then Hgi::SubmitCmds is never called for a non-Storm renderer.
Thus garbage collection never runs.

I'll see if I can get us to commit putting Hgi::EndFrame in place finally.

**Comment by marsupial** [comment]
Great news! Please let me know when it makes it in.

Thanks.

**Comment by sunyab** [comment]
This should be addressed by cd63a6f, which was just pushed to the dev branch.

**Comment by marsupial** [comment]
Perfect, thanks!
