### ISSUE TITLE
[usdImaging] drawMode requires applied GeomModelAPI schema in USD 20.11

### ISSUE THREAD

**Issue by fabal** [PixarAnimationStudios/USD#1401]
### Description of Issue
This is more of a question than an actual issue (which would be a good candidate for using the new github discussions feature): since https://github.com/PixarAnimationStudios/USD/commit/ccf9a3ddc8cdaf8ec9d5867418ebc947ca00d799, a `GeomModelAPI` schema must have been applied to a prim for the `drawMode` attribute to take place (on top of the fact that the prim has to be a model too). Would it be possible to clarify the rationale behind this extra requirement?

### Package Versions
* USD 20.11+

**Comment by spiffmon** [comment]
Hi @fabal ,
   We haven't discussed yet whether it makes sense to activate discussions for our repo, given the vibrancy of usd-interest, so I'll answer here, for now.
    Ever since we completed the work, in 20.05, of incorporating applied API schemas into _the type of a prim itself_ (which is known as a UsdPrimTypeInfo), we have been slowly converting code to make use of this awesome feature.  UsdGeomModelAPI was always an applied schema, but when applied schemas were under-powered, there was little point, and extra cost, to our code (or yours) being strict about ensuring the schema was applied properly.
   But since 20.05, applied schemas now have at least two added, important characteristcs:

1. They contribute to a prim's **definition**, i.e. all of their defined properties become _builtins_ of whichever prims to which they are applied.  So when UsdGeomModelAPI is properly applied to a prim, you will see all of the UsdGeomModelAPI properties in usdview's property inspector, and in property enumeration and interrogation methods.
2. UsdPrim::HasAPI() is now an optimized, upfront cached query.  Imaging (and other code) previously had to do several more expensive property value queries on every model prim to determine what drawMode properties might be present and needed, even though relatively few prims may have any such data.  Now imaging can do a simple HasAPI() call as a fast-reject test before querying any properties.

As we're always trying to make USD faster, #2 was our primary motivation, here.  We hope to enable such a HasAPI test in imaging for UsdShadeMaterialBindingAPI soon, which is also typically very sparsely authored, with many properties to query.

Hope that makes sense!
--spiff

**Comment by jilliene** [comment]
Filed as internal issue #USD-6495

**Comment by fabal** [comment]
Thanks @spiffmon it makes sense.
The thing is that we author the `drawMode` attribute using Sdf (inside a SdfChangeBlock) without applying the GeomModelAPI schema (because doing so to a primSpec is not that easy unless you could provide a nice snippet :smile: ). This means that our assets won't display properly in USD 20.11 and we will have to generate the assets again.
I just wanted to flag this in case other naughty people not authoring the attribute via the applied API schema hit the same issue. In the CHANGELOG, it's mentioned "Changed texture cards to require prims with UsdGeomModelAPI schema applied" which is a good start but I would think that it's not specific to texture cards only, is it?

**Comment by spiffmon** [comment]
Are you coding in python or C++?

**Comment by fabal** [comment]
This part authors in python.

**Comment by spiffmon** [comment]
With thanks to Corey Revilla, this should do the trick for appending, though you can prepend or assign to the listOp, alternatively:
```
lop = sdfPrimSpec.GetInfo('apiSchemas')
lop.appendedItems = lop.appendedItems + ['GeomModelAPI']
sdfPrimSpec.SetInfo('apiSchemas', lop)
```

**Comment by fabal** [comment]
We updated our code with something along those lines however I wish we could "apply" the schema directly onto a primSpec instead of having to dive into the forensics.

**Comment by spiffmon** [comment]
Well, "apply" is a UsdPrim-level concept, so it can't really be represented at the lower, Sdf-level.  We do have a batch-editing-for-Usd project on the books for next year, so hopefully that will provide a more palatable, performant solution.

**Comment by fabal** [comment]
Sure, it's just that one needs to use a rather low level API (explicitly flagged as _interim_ by the way) in that case instead of a first class one.
Thanks for your help and looking forward to trying the USD batch editing tool out :smile:
