### ISSUE TITLE
Memory leak when using static tokens predefined in USD

### ISSUE THREAD

**Issue by zpgit** [PixarAnimationStudios/USD#1428]
### Description of Issue
pxr::UsdGeomTokens->y is used when setting the up axis.
pxr::UsdGeomSetStageUpAxis(stage, pxr::UsdGeomTokens->y);
Memory leak is detected by VLD tool.

pxr::KindTokens->component is used when calling SetMetadata()
partPrim.SetMetadata(pxr::SdfFieldKeys->Kind, pxr::KindTokens->component);
Memory leak is detected by VLD tool.

### Steps to Reproduce
1. Call the APIs mentioned above with predefined tokens as parameters.

**Comment by spiffmon** [comment]
Hi @zpgit !  Thanks for taking an interest in USD!  This "leak" is intentional: we declare known, commonly-used TfTokens to be "immortal", which exempts them from reference-counting (at the cost of them never being freed), which measurably improves the performance of many of our multi-threaded core algorithms.  IIRC, the cost is only a few Mb.  If the leak is annoying to your profiling, you may be able to suppress it.
