### ISSUE TITLE
Py_IsInitialized() error on Mac with Python 3.7.5

### ISSUE THREAD

**Issue by onikolas** [PixarAnimationStudios/USD#1430]
### Description of Issue
After building the library with python 3.7.5, if I run any usd tool I get the following error:

> python3.7 crashed. FATAL ERROR: Failed axiom: ' Py_IsInitialized() '
> in operator() at line 148 of homefolder/USD/pxr/base/tf/pyTracing.cpp

### Steps to Reproduce
1. Install python 3.7.5 through pyenv
2. Build using .pyenv/versions/3.7.5/bin/python3.7  USD/build_scripts/build_usd.py build-location --no-usdview
3. Export paths as instructed
4. Run any of the tools (such as usdcat) or import pxr

**Comment by rstelzleni** [comment]
I've never tried to build with pyenv on Mac, but I might be able to give it a try later and see if the problem reproduces for me. If that check fails it might mean that while bootstrapping the python interpreter, the current interpreter either isn't the right python version, or it is the same version but it isn't ABI compatible with the interpreter USD was built against. It could also mean that the interpreter is getting a python shared lib that isn't ABI compatible. That might be more likely, since I think on Mac the interpreter path is put into the usdcat `#!` directly.

I think the first thing I'd check is whether the pyenv environment for python3.7 is being activated when you invoke usdcat. A quick way to check would be to set the env var `PYENV_VERSION` to point to 3.7.5 and see if that gets usdcat to work.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6541

**Comment by onikolas** [comment]
It seems that pyenv installs a version that is not built with shared python library enabled.

I built python3.7.5 from source (passing --enable-shared to configure) and it works. Installing a _-dev_ version with pyenv might also work but haven't tried it.
