### ISSUE TITLE
UsdTransform2d get fail with ComplianceChecker (ARKit=True)

### ISSUE THREAD

**Issue by thang12l** [PixarAnimationStudios/USD#1444]
### Description of Issue
USDZ with shader node id UsdTransform2d get fail witl ComplianceChecker for ARKit mode.
Current  ARKitShaderChecker check accepts only UsdPreviewSurface, UsdUVTexture or UsdUVTexture as the shaderId.

### Steps to Reproduce
usdARKitChecker frame_Merlo.usdz

### System Information (OS, Hardware)
Linux

### Package Versions
USD 19.11
usdconvert 0.64

### Build Flags

[frame_Merlo.zip](https://github.com/PixarAnimationStudios/USD/files/5940889/frame_Merlo.zip)

**Comment by spiffmon** [comment]
Hi @thang12l ,
   The issue you are reporting is with Apple software, and you need to file it with them. Fwiw, I think the compliance checker is just being honest with you, because Apple indeed does not yet support the Transform2d shader. It was added to the spec after Apple had launched Arkit-with-usdz, but hopefully they will support it soon. But you’ll need to ask them!

**Comment by hybridherbst** [comment]
I think this should be reopened - QuickLook now supports UsdTransform2d (albeit with issues that I reported to them), yet the checker still says it doesn't.
