### ISSUE TITLE
Version consistency

### ISSUE THREAD

**Issue by seando-adsk** [PixarAnimationStudios/USD#1493]
### Description of Issue

In the file "cmake/defaults/Version.cmake" the previous USD versions were 21.02/21.05, but the current one is 21.8 (no 0). Does this matter for consistency?

**Comment by c64kernal** [comment]
Thanks for calling this out -- we should fix this.

**Comment by sunyab** [comment]
Hi @seando-adsk, this was intentional. Using a leading '0' causes C++ to recognize the value as an octal number which causes a variety of errors (e.g., '08' is not a valid octal number). The usual pattern was to leave off the leading '0', but we mistakenly reintroduced it in 21.02 and 21.05.

Let us know if there's any other questions, otherwise I'll close this out. Thanks for asking!

**Comment by spiffmon** [comment]
This is actually intentional, and unfortunate,  Windows wants to convert the "08" in Version.cmake to octal, which we do not want.  So, like previous "third releases of the year", we work around by using simply "8" instead of "08" even though it causes an inconsistency.

See, for example, [last year's 20.08 commit](https://github.com/PixarAnimationStudios/USD/commit/9000944d95e0d3f36ce17108f97b1607778b7540#diff-ad5cb413debbd5c768a61d452c9243982d5f7f61950c44271e63afea15f0e443)

**Comment by c64kernal** [comment]
Apologies for the crossed wires.
