### ISSUE TITLE
[usdrecord] Prevent Qt window from showing

### ISSUE THREAD

**Issue by pmintus-atvi** [PixarAnimationStudios/USD#1521]
### Description of Issue
usdrecord creates a glWidget window that it hides _after_ displaying it. On Windows, this causes the window to show up for a split second and then disappear. The window doesn't just cause a visual artifact, it also steals input focus since the window is created top-level. When usdrecord is used in a batch process, these windows blink into existence and flood the user's desktop. 

### Steps to Reproduce
1. Execute usdrecord

### System Information (OS, Hardware)
Windows 10 20H2

### Package Versions
21.05

**Comment by pmintus** [comment]
I plan on submitting a fix for this.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6701

**Comment by tallytalwar** [comment]
Instead of doing a widget->show and then widget->hide, we can simply set the gl context to be current, which will **NOT** make the qt widget show up. Note that we simply need to record the framebuffer in an image and do not want to show the gl widget.
This change prevents the usdrecord window from being displayed for a split second. An change has been made for the same internally and should go out in the next dev branch push.
