### ISSUE TITLE
usdzip is not replacing layer paths correctly

### ISSUE THREAD

**Issue by mibu138** [PixarAnimationStudios/USD#1543]
### Description of Issue
usdzip utility does not correctly replace layer paths to archived sublayers. Neither does the C++ function UsdUtilsCreateNewUsdzPackage. 

### Steps to Reproduce
1. Download the attached zip file and unzip it. 
[usdztest.zip](https://github.com/PixarAnimationStudios/USD/files/6697046/usdztest.zip)

2. In shell at location of unzipped archive: `usdzip shot.usdz simpleshot/shot/shot.usd` 
3. Running `usdtree --flatten shot.usdz` will report a warning: ```Warning: in _ReportErrors at line 2825 of /home/michaelb/dev/USD/pxr/usd/usd/stage.cpp -- Could not load sublayer @/tmp/shot.usdz[simpleshot/set/set.usd]@ of layer @/tmp/shot.usdz@; skipping. (instantiating stage on stage @/tmp/shot.usdz@ <0x12c95b0>)``` indicating it was unable to load a sublayer.
4. Running `usdcat shot.usdz` will show the path to the sublayer as `@../set/set.usd@`, which is the original layer path. So it appears this is not being correctly replaced with the new path when the archive is created.

### System Information (OS, Hardware)
Ubuntu 20.04 
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
x86_64

### Package Versions
Tested and reproduced on today's dev and release builds

### Build Flags
  -DOPENSUBDIV_ROOT_DIR=$HOME/dev/OpenSubdiv/build 
  -DOPENSUBDIV_INCLUDE_DIR=$HOME/dev/OpenSubdiv/build/public_headers 
  -DPTEX_LOCATION=$HOME/dev/ptex/install 
  -DPXR_USE_PYTHON_3=ON

**Comment by jilliene** [comment]
Filed as internal issue #USD-6762

**Comment by sunyab** [comment]
Hi @mokchira, I just wanted to double-check that you had put in the correct command line in your repro steps above? 

By default, `usdzip` just adds exactly the files you specify -- it does not walk dependencies to add referenced/sublayered/etc. files and does not update any paths to point to new locations. The command line you posted will just create a .usdz file with only `simpleshot/shot/shot.usd` in it, which is why you wind up getting the error message saying that `simpleshot/set/set.usd` can't be found. If I run: `usdzip shot.usdz simpleshot/shot/shot.usd simpleshot/set/set.usd` then everything appears to work as I'd expect.

Now, if you run `usdzip -a simpleshot/shot/shot.usd shot.usdz`, that *should* walk the dependencies of shot.usd and add referenced layers, etc. That doesn't seem to be working, and I'll be looking into that further.  But I just wanted to mention the above in case that was helpful.

**Comment by mibu138** [comment]
Ah thanks for pointing that out. Yeah I was unaware I needed to use the -a flag to get all the dependencies included in the zip. I actually dug a bit and found that the C++ function UsdUtilsCreateNewUsdzPackage() was not working correctly, which is documented to package up all the dependencies, and I assumed that the usdz cmdline tool was basically just calling that. 

Might I ask why that's not the default behaviour? If the default behaviour is to only include the files you specify, isn't that the same as just using vanilla zip?

**Comment by drwave** [comment]
Well, I for one like the current behavior.

Many times I will usdzip up a USD file and only want the texture files associated with the default variant, not all the other ones, so I like to be able to hand in a command line that just has those specific texture files in it.

But if I want it to go find everything, I have that option.


- wave

**Comment by spiffmon** [comment]
One reason for the current default behavior is that initially, making a usdz that was compatible with the Apple tool chain required some tweaks and limitations that were undesirable for other uses, so there needed to be two different “asset” modes. The validation process is still different for Apple usdz, as it supports a more limited feature set.

**Comment by sunyab** [comment]
We believe the original issue was fixed by 09a4df53, which was included in the 23.05 release. Closing this out, thanks!
