### ISSUE TITLE
Error in super basic program.

### ISSUE THREAD

**Issue by stormsc1** [PixarAnimationStudios/USD#1598]
### Description of Issue
Error in super basic program, i have no idea what is wrong?

### Steps to Reproduce
1. Download and build USD without python
2. Add includes: `%USDROOT%/include` and `%USDROOT%/include/boost-1_70
3. Add libraries: `tbb_debug.lib`, `ar.lib`, `kind.lib`, `sdf.lib`, `tf.lib`, `vt.lib`, `pcp.lib`, `usd.lib`, `usdGeom.lib`, `usdPhysics.lib`,  `usdShade.lib`, `usdRi.lib` and `usdUtils.lib`
4. Copy corresponding dlls to the build folder.
5. Add a main.cpp file with the following code:
```c++
#define _CRT_SECURE_NO_DEPRECATE
#define _CRT_NONSTDC_NO_DEPRECATE
#define NOMINMAX
#define YY_NO_UNISTD_H

#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usdGeom/sphere.h>

int main() {
    auto stage = pxr::UsdStage::CreateInMemory();
    return 0;
}
```
Error:
```
Coding Error: in CreateAnonymous at line 298 of C:\Dev\USD\pxr\usd\sdf\layer.cpp -- Cannot determine file format for anonymous SdfLayer
Coding Error: in Open at line 1043 of C:\Dev\USD\pxr\usd\usd\stage.cpp -- Invalid root layer
```

I tried this on two machines with the same result.

### System Information (OS, Hardware)
Windows 10, NVIDIA, Intel

**Comment by meshula** [comment]
This means the plugins (including file format plugins) have not been registered, which usually happens if your environment is not set up with the paths indicated at the completion of the USD build.

**Comment by stormsc1** [comment]
Shouldn't this be setup automatically by the python build script? If not, how do i go about fixing it; i don't know what environment variables you are referring to?

EDIT: I found the paths, but it still doesn't work.
![image](https://user-images.githubusercontent.com/36606323/129974726-1881bc6c-e253-49fe-af90-878963792acd.png)

**Comment by meshula** [comment]
I just re-read your build instructions more carefully. Your fourth step "Copy corresponding dlls to the build folder" isn't enough. USD has a dynamic loading mechanism, and it uses some json files  in the installation to find all the plugins to initialize itself; USD needs all of the dlls in the build, not just the corresponding ones, and it uses some heuristics to discover the json files. I'd suggest not trying to work around those heuristics when you are trying this for the first time.

As an easier first step, I suggest moving your executable into the C:\usd\bin folder, and run your executable there, with C:\USD\bin and C:\USD\lib in your environment's PATH variable. 

Once you have your program working c:\USD\bin, if you want to package your app up outside of there, you'll be in a much better starting place to do it.

**Comment by stormsc1** [comment]
Nice, moving the .exe into the bin folder works; now what dlls do i actually need and how would i go about putting this into a shippable package? 

EDIT: I am not able to find anything about this in the docs? Do you know where the documentation regarding this can be found?

**Comment by meshula** [comment]
Now, you're in the realm of the usual cmake stuff.

If you look in your installation, you should be able to find a file called pxrConfig.cmake ~ in my installation, it's add C:/Projects/USD-install/pxrConfig.cmake, If you look at that script, the libs variable has the answer to your question about DLLs.

I can't tell you the contents of that variable, it depends on your build. You will also need the dlls those dlls need, which you can learn with a program like dependencywalker.exe. Usually people manage this part of bundling with a bundling tool or script; I don't have a particular one to recommend.

You will also need to copy the plugins directory, and it needs to be relative to your exe in the same way as it is currently, at your.exe/../plugins. There is a way to configure the location in code, if you investigate the Plug library.

Once you are comfortable with building USD for windows, you might consider investigating the "monolithic static" build. It is much easier to manage on Windows because the only external dependency becomes the plugins folder. Before you take that on though, you should know how the plug library finds that folder so that you can set things up the way you like.

**Comment by stormsc1** [comment]
Thx! I have been stuck on this for a while, you really helped me out here! I still can't find any documentation describing what you are saying here tho?

EDIT: To give you some context, I am trying to use USD as the scene format of an application i am working on.

**Comment by stormsc1** [comment]
Having done a bit of testing, it seems like building in debug and release link differently as well?

**Comment by stormsc1** [comment]
> Usually people manage this part of bundling with a bundling tool or script

I suppose you are taking about something line ILMerge?

**Comment by meshula** [comment]
Yes, debug and release link differently. There is work underway to accomodate a full debug build of USD, but I think it is not yet landed. I personally use the RelWithDebInfo targets in preference to Debug, and turn off optimizations in code that I want to debug in detail. I do this because Microsoft's STL performance is very slow in debug mode, and you need to have knowledge of a bunch of preprocessor directives to get performance back; those directives in turn cause linking problems, since they change interfaces on for example, vector iterators. All of this complexity isn't worth it to me, and it goes away with RelWithDebInfo + optimization off selectively.

I was thinking of tools like InstallShield or Wix. ILMerge won't help in USD's case because it's targeted to .NET assemblies, but yes, it's in the category of smart bundling tools.

**Comment by stormsc1** [comment]
So how would i go about linking to a project with both debug and release configurations, i plan to just use precompiled binaries?

**Comment by meshula** [comment]
I recommend following this pull request - https://github.com/PixarAnimationStudios/USD/pull/1478 - which explores the question of Debug builds in great detail.

**Comment by meshula** [comment]
Also this issue - https://github.com/PixarAnimationStudios/USD/issues/1570

**Comment by stormsc1** [comment]
Thx!
