### ISSUE TITLE
convert vertex normals to face normals

### ISSUE THREAD

**Issue by lovettchris** [PixarAnimationStudios/USD#1611]
### Description of Issue

I'm converting .obj to .usd and it appears I have to convert .obj vertex normals to face normals.  Is there a utility in the USD library that can do that for me?

### Steps to Reproduce
```python 
meshPrim = UsdGeom.Mesh.Define(stage, '/World/Mesh')
meshPrim.GetPointsAttr().Set(points)
meshPrim.GetNormalsAttr().Set(normals)
meshPrim.SetNormalsInterpolation(UsdGeom.Tokens.vertex)
meshPrim.CreateSubdivisionSchemeAttr(UsdGeom.Tokens.subdivisionScheme).Set("none")
```

I was hoping this would be able to interpolate my vertex normals, but it doesn't render properly.  It would be nice if USD could interpolate vertex normals because the usd file would be a lot smaller.  I have many more faces than vertices.  I have 1,766,987 vertices and 3,525,185 faces.

![image](https://user-images.githubusercontent.com/18707114/132077038-c022fe91-dba8-4481-ab4d-11b12fb56e5e.png)

### System Information (OS, Hardware)

Windows 11, AMD Ryzen 9, NVIDIA 1080

### Package Versions

usd-core                                21.8

### Build Flags
N/A

**Comment by lovettchris** [comment]
hmmm, hang on... maybe I misunderstood, I think my problem is len(normals) != len(GetFaceVertexIndices), so I'm fixing that, but weird I still have the problem... so maybe it is not a normals problem, but an arnold texture mapping problem...

**Comment by spiffmon** [comment]
Just to clear up a couple of things, @lovettchris  :
1. UsdGeomMesh _does_ support _vertex_ normals, as well as _uniform_, _varying_, and _faceVarying_, but...
2. As the documentation states (it can be overlooked, as the documentation is voluminous in order to be precise), normals on Mesh prims are **only relevant at all** if the Mesh's _subdivisionScheme_ is set to "none", because subdivs compute natural, analytic normals through OpenSubdiv that follow the features of the surface.  SO if you want your authored normals to "stick" in compliant renderers, you need to author _subdivisionSchem = "none"_ also.

**Comment by lovettchris** [comment]
Awesome, thanks for responding.  So I have verified that my vertex normals are working with subdivisionSchem = "none" .  I found the bug with my texture mapping conversion, I was incorrectly computing my `texCoord2f[] primvars:map1` and `int[] primvars:map1:indices` values.  So I'm now able to import my 3d reconstructed .obj into usd and view it with usdview, yay!

![image](https://user-images.githubusercontent.com/18707114/132083226-5bf49edf-398a-4da3-b420-cab61c432a25.png)
