### ISSUE TITLE
Discussion: Shaders and Texture Path Expressions

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#1637]
Hi, 
This isn't an issue, but wishes to discuss this with you.

1. Does USD support referencing textures paths using expressions that relies on primitives variables? (something like this: <userProperties.tex_dir>/<userProperties:name>.tex)
2. When USD refers to the assigned shader, can this be as an expression as well using the same method above also based on primitive variables?

If none of the above is possible, then where in the API (or in which library) could something like this be developed and implemented the way that allows any renderer to get the shaders and textures resolved in rendertime based on such expressions? In other words, what is the USD library that any renderer should call to parse the usd stage to be rendered? And if what I'm thinking of is possible at this manner?

**Comment by spiffmon** [comment]
These are great questions!
1. USD does not currently support any substitutions other than \<UDIM\> in texture paths.  We have a task on our backlog to support **primvar** substitutions (as well as some other stage-global variables) that I would really like to see us get to.  It just hasn't been a priority for us (and is not a small task) because it is only relevant for us in our RenderMan pipeline, where Katana performs the substitutions, post-USD and without Hydra involvement.  As we move to direct Hydra rendering, it should become more of a priority.
2. We have a project on our Roadmap that will likely start early next year called "pattern-based collections", which will allow UsdCollectionAPI collections to be defined in terms of CEL-like expressions (which will likely not include the ability to reference primvars due to expense/scalability, but that decision has not been made yet).  When this feature lands you will automatically be able to bind Materials using this mechanism thanks to "collection based material bindings".

So, it's all coming, but we beg your patience.

**Comment by BSalem** [comment]
Sounds interesting, thanks for sharing this information... looking forward to see it happening.

**Comment by BSalem** [comment]
I still hope to see this happening -:) Any updates or progress on it?

Our pipeline with Seneferu doing really efficient and nice shading, look and texture resolving based on variables and primvars in katana and renderman, we do the same substitutions in Solaris and Maya as well, however it would be super nice to have such methodology handled by USD itself, so we can have such nice methodologies delivered to everywhere, especially to those applications which cannot do such substitutions on top of the USD layer (like usdview, omniverse... etc)
