### ISSUE TITLE
_GetPythonLibraryFilename function in build_usd.py doesn't account for pymalloc suffix on MacOS

### ISSUE THREAD

**Issue by mhamid3d** [PixarAnimationStudios/USD#1724]
Users who have their python library compiled with `pymalloc`, meaning their python library looks like this:

`libpython3.7m.dylib`

instead of:

`libpython3.7.dylib`

will encounter an error while building, as the `build_usd.py` file is explicitly constructing the library name on MacOS. 

this part of the `_GetPythonLibraryFilename` function on like 206 `build_usd.py`
```
elif MacOS():
    return "libpython" + pythonVersion + ".dylib"
```

should probably be like this instead:

```
elif MacOS():
    pythonVersion = sysconfig.get_config_var('LDVERSION') or sysconfig.get_config_var('VERSION')
    return "libpython" + pythonVersion + ".dylib"
```
This is the method used on the `maya-usd` for grabbing the python version across all platforms, so maybe it could be used globally on the `pythonVersion` variable instead of just in the `MacOS` elif statement.

I'm not sure why `"py_version_short"` is used as opposed to `"VERSION"` or `"LDVERSION"`, maybe someone could offer an explanation.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7095

**Comment by sunyab** [comment]
Thank you for the suggestion! I think I wound up using `py_version_short` out of convenience since it seemed to be present in all the various Python configurations I tried, and we ended up needing that exact string for other purposes. I'll look at implementing this fix shortly.

(As an aside, I really wish build_usd.py didn't have to be in the business of trying to figure all this stuff out. I'd love to dump all of this in favor of something like find_libpython but I haven't had time to try it)
