### ISSUE TITLE
UsdUtilsComputeAllDependencies does not return composed list ops

### ISSUE THREAD

**Issue by roggiezhang-nv** [PixarAnimationStudios/USD#1750]
### Description of Issue
Is that defined that UsdUtilsComputeAllDependencies will not bake list ops? I want to use that to compute the layer's dependencies, however, it will not only return those added items, but also deleted items.

### Steps to Reproduce
1. Download [repro.zip](https://github.com/PixarAnimationStudios/USD/files/7905110/repro.zip).
2. Calling `UsdUtilsComputeAllDependencies` to `replacement.usda`. And `replacement.usda` includes a snippet like:

```
def "RootNode"
{
    def "prim" (
        delete references = @./meshes/b.usda@
        prepend references = @./meshes/a.usda@
    )
    {
    }
}
```

After calling `UsdUtilsComputeAllDependencies` to compute the dependencies, it will not only return the prepend items, but also the deleted references. Is this exepcted?

### System Information (OS, Hardware)
Windows.

### Package Versions
21.08.

**Comment by asluk** [comment]
Verified Roggie's repro in the latest dev branch as well using the python interpreter in usdview

I would not expect b.usda to show up in the dependencies, as it has been deleted in the references listop.

Thanks for looking!

>>> UsdUtils.ComputeAllDependencies( usdviewApi.stage.GetRootLayer().identifier) 

([Sdf.Find('c:/Users/aluk/Downloads/repro/replacements.usda'), Sdf.Find('c:/Users/aluk/Downloads/repro/meshes/b.usda'), Sdf.Find('c:/Users/aluk/Downloads/repro/meshes/a.usda')], [], [])

**Comment by spiffmon** [comment]
I would call this expected behavior, based on both the philosophy and actual mechanism of how the dependency extractor works.  The problem we are trying to solve, here, is to find dependencies for a layer such that, if you put the layer on a Stage, then switching any VariantSet to any of its possible values, or **muting** any layer should still give you a (as valid as the original) valid Stage, which pulls in only the discovered and isolated results.

So, if you were to mute a layer that **deleted** a given subLayer, then the subLayer would be needed by the stage.  

It's true that in @roggiezhang-nv 's case, you can't mute the deletion because it is brought in by reference... but to **know** that definitively, we would either need to operate on a fully composed stage (and you can already get that result by asking the stage for its GetUsedLayers(), though it won't include textures, etc.) in which case we'd only be processing a single Variant for every VariantSet, or we'd need to reimplement chunks of the composition algorithm and significantly complicate the (currently pretty simple, recursive-by-layer) algorithm that the dependency extractor uses.

We could probably document the expected behavior better, but this is a tradeoff for gathering "all of the things the stage _could_ depend on in some configuration.

**Comment by roggiezhang-nv** [comment]
Thanks for your answer, Spiff. I'll close this as expected behavior currently.
