### ISSUE TITLE
Plugin resolver creation fails with libc++ on Linux with -fvisibility=hidden

### ISSUE THREAD

**Issue by abbec** [PixarAnimationStudios/USD#1752]
We are building a custom resolver plugin (V1) against the USD version that ships with Unreal engine (4.27) for Linux. However, we run into a problem where our resolver fails to be created. More, specifically, it fails with [this](https://github.com/PixarAnimationStudios/USD/blob/faed18ce62c8736b02413635b584a2f637156bad/pxr/usd/ar/resolver_v1.cpp#L185) message.

We have debugged it to be a failure inside `dynamic_cast` as that is used [here](https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/pxr/base/tf/type.h#L637) when retrieving an `Ar_ResolverFactoryBase` instance to construct the resolver.

The copy of USD that ships with Unreal is built with the LLVM libc++ standard library and the implementation of `dynamic_cast` in there differs quite significantly from the one in GNU libstdc++ in that the `type_info` comparisons done in libstdc++ (the GNU one) uses `strcmp` to compare types.

When including `defineResolver.h` inside our plugin, we end up with a `Ar_ResolverFactoryBase` that, when using libc++ (the LLVM one) is a different type than the one in `resolver_v1.cpp`. This causes the `dynamic_cast` to fail and the resolver instance cannot be constructed. The same code works fine when USD is built against `libstdc++` (a choice that we do not have with Unreal).

Since the above explanation is most likely lacking in a lot of ways, we have also created a minimal example that reproduces the issue [here](https://github.com/goodbyekansas/cast-away). The example has replaced `Resolver` with `Ship`, otherwise it aims to be very similar to the actual code in USD.

**Comment by abbec** [comment]
There is some information on the issue here: https://gcc.gnu.org/faq.html#dso and adding the `--export-dynamic` linker flag to the main program in our [repro example](https://github.com/goodbyekansas/cast-away) does solve the issue. Is this something that can be done with `libar.so` by default (it needs to be done on the program/dso that does `dlopen`)?

**Comment by abbec** [comment]
Actually, scratch what I said earlier, it seems to be that USD is somehow built with hidden visibility (`-fvisibility=hidden`). In these cases, `Ar_ResolverFactoryBase` is missing `AR_API` causing it to be private, causing `dynamic_cast` to fail with libc++.

**Comment by abbec** [comment]
I have also updated the [repro](https://github.com/goodbyekansas/cast-away) to better match this case.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7162

**Comment by sunyab** [comment]
Hello @abbec, thank you for the fantastic repro case. As you mention, the main issue here is the use of hidden visibility. USD currently does not support this for a variety of reasons -- in particular, see #665 and #1475. I'm surprised the USD build works properly. It seems like the source code would need a large number of modifications to get this to work. 

Since we don't support `-fvisibility=hidden` at all right now I am hesitant to take on this fix without addressing the bigger problems in the issues above. Since any such fix would have to be pulled in by Epic into a new release anyway, I think it would be good to raise this issue with them and see how/why they're building with hidden visibility and ask if they can stop doing so, given USD's current lack of support for it.

**Comment by abbec** [comment]
Actually as it turns out, Unreal does not build with hidden visibility. The symptoms are similiar but the cause is likely something different which we have not had the time to look in to yet. Therefore, this issue was repurposed to cover the general (non-Unreal) case. I.e. we do not need this for Unreal support so it is not urgent :)
