### ISSUE TITLE
Partially cast NdrNodes found in SdrRegistry::GetShaderNodesByFamily() results

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1836]
### Description of Issue

Undefined behavior trying to read shader information from SdrRegistry(). System crashes or becomes unstable.

### Steps to Reproduce

1. Use a discovery plugin that generates NdrNodes, like [Arnold-USD](https://github.com/Autodesk/arnold-usd/blob/master/ndr/parser.cpp#L144)
2. Use any SdrRegistry API that returns a SdrShaderNodePtrVec
3. Use functions that are specific to SdrShaderNode on a vector item that is actually an incorrectly cast NdrNode.

Result: At best: uninitialized values, at worst: a crash.

### Fix

Use `std::dynamic_pointer_cast<SdrShaderNode>` in [NdrNodeVecToShaderNodeVec()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/sdr/registry.cpp#L48) and skip nullptrs created by failure to downcast to SdrShaderNode*.

### System Information (OS, Hardware)

Found in USD 21.11 Windows Release

**Comment by spiffmon** [comment]
Apologies for the confusion, @JGamache-autodesk . It would be great for us to avoid UB, here, but what the Arnold plugin is doing is in no way supported - it should be creating and returning SdrShaderNodes.  Our long-term plan is to "retire" Ndr, merging it up (in a backwards-compatible way) into Sdr so that there is **only** Sdr to deal with.  We thought initially we might have other "*dr" specializations of Ndr, but as we got into it, Sdr seemed reasonable for every new need that has come up so far, and the bifurcation just adds overhead (and here, confusion).

**Comment by JGamache-autodesk** [comment]
Thanks for the information @spiffmon. I will open an issue on the Arnold-USD tracker to go back to producing SdrShaderNodes.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7335
