### ISSUE TITLE
UDIM higher than 1100 is broken in usdview

### ISSUE THREAD

**Issue by zephchai** [PixarAnimationStudios/USD#1846]
### Description of Issue
Hi,

I found a problem when viewing an asset that has udim higher than 1100 in usdview.
![broken_material](https://user-images.githubusercontent.com/12978881/165868428-c7cff9fc-84aa-47be-9d6d-31ccbea8f80f.png)

The usd version I am using is 21.11. It works fine if I shift the UV within 1100 so it looks like the texture is not being read if the udim is higher than 1100.

I have attached an example in the zip file to illustrate the problem.
[udim_bug.zip](https://github.com/PixarAnimationStudios/USD/files/8587436/udim_bug.zip)

### Steps to Reproduce
1. Unzip the attached zip file to a folder
2. Use usdview to open cube.usda
3. Rotate the cube so that you are viewing the bottom. You should see that the material is broken.
4. In the usda, there are 2 lines of st values with 1 commented out. One is working and the other is broken.

### System Information (OS, Hardware)
Windows10, Kubuntu 18.04

### Package Versions
USD 21.11 and earlier

Thanks

**Comment by zephchai** [comment]
Looking at the code, I may have the found the cause.

I found this line in 2 files
`static const int UDIM_END_TILE = 1100;`

USD-21.11\pxr\imaging\hdSt\udimTextureObject.cpp:44
USD-21.11\pxr\usdImaging\usdImaging\materialParamUtils.cpp:56

Since UDIM supports up to 9999, ending at 1100 may seems limited. Although I also agree that it is not common for UDIM to go over 1100. Any thoughts?

Thanks,
Zeph

**Comment by spiffmon** [comment]
Hi @zephchai ,
   Yes, as you guessed in the usd-interest thread, this cap is set for performance reasons, since resolving assetPaths can expensive.  Now for sure the codesites you found could be parallelized over the tiles, but there should already be per-prim multithreading, and it sould not change the total amount of required computation.  Are there scenarios in which you actually have **more** tiles than our limit allows?

   I would propose that the "fix" for this Issue be actually documenting the limit [here](https://graphics.pixar.com/usd/release/spec_usdpreviewsurface.html#texture-reader) (which I'm surprised isn't there already)?

--spiff

**Comment by zephchai** [comment]
Hi @spiffmon, 

Thanks for your reply. We do have assets going over the limit but I will let people in production know about this and hopefully they can work within the limit. And I agree this should be documented.

Thanks again. I will close this issue then.

**Comment by spiffmon** [comment]
@zephchai , I'm reopening the issue because it explains the issue well, and it can serve as a task for us to do the documentation, and possibly the configurability that Colin E mentioned on usd-interest.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7356
