### ISSUE TITLE
building usd with namespace lacks some classes

### ISSUE THREAD

**Issue by iqch** [PixarAnimationStudios/USD#186]
some our houdini plug-ins built against usd libraries with namespaces cries about next issues.
 undefined symbol: _ZTI19VtStreamOutIterator

buiding against non-namespace using usd libraries doesn't produce such troubles and work fine.

we link those plug-ins with such cmake instruction
 link_libraries(
        HoudiniAPPS2 HoudiniGEO HoudiniPRM
        HoudiniOP1 HoudiniOP2 HoudiniOP3 HoudiniOPZ
        ar usd usdGeom tf sdf pcp arch)

CentOS7 x64, Houdini16.0.504.20
usd v0.7.4

**Comment by jtran56** [comment]
Filed as internal issue #144791.

**Comment by sunyab** [comment]
@iqch: Since the undefined symbol is not in a namespace, it looks like your Houdini plugin build is not getting the right namespace-wrapped code when you include the USD headers. This should be fixed if you add -DPXR_USE_NAMESPACES when you build your Houdini plugin. Can you give that a try?

This is needed right now because the namespaces aren't enabled by default in USD. Once we switch them on by default, you shouldn't need to specify any extra defines to build against the namespace-enabled USD.

**Comment by sunyab** [comment]
Closing out old issue, please let us know if you're still running into problems here. Thanks!
