### ISSUE TITLE
TestPlugUnloadableDso doesn't compile on Windows

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#199]
Would be nice to jig this test for compilation on Windows as well. It's the only thing not compiling from ToT dev.

````
"C:\Projects\usd\stage\prereq\build\USD\install.vcxproj" (default target) (1) ->
       "C:\Projects\usd\stage\prereq\build\USD\ALL_BUILD.vcxproj" (default target) (2) ->
       "C:\Projects\usd\stage\prereq\build\USD\pxr\base\lib\plug\TestPlugDsoUnloadable.vcxproj" (default target) (15) ->
       (Link target) ->
         TestPlugDsoUnloadable.obj : error LNK2019: unresolved external symbol "int __cdecl TestPlugDoSomethingUndefined(void)" (?TestPlu
       gDoSomethingUndefined@@YAHXZ) referenced in function "void __cdecl `dynamic initializer for 'something''(void)" (??__Esomething@@Y
       AXXZ) [C:\Projects\usd\stage\prereq\build\USD\pxr\base\lib\plug\TestPlugDsoUnloadable.vcxproj]

````

**Comment by jtran56** [comment]
Filed as internal issue #145408.

**Comment by crs23** [comment]
Just FYI the test is building correctly. It's deliberately missing a symbol (that's the test) so the link command has /FORCE:UNRESOLVED. Instead of linking silently, the linker still reports the error you're seeing and it adds a warning that the link was performed anyway. I think neither the error nor the warning can be suppressed but this could hopefully be less confusing.

**Comment by meshula** [comment]
Gotcha, good to know that's the intention, and that the test is functioning as designed.

I'll double check that cmake is returning success at the end of the build that includes the designed failure and then update this ticket. A clean overall result code is all I really need, so that automation succeeds.
