### ISSUE TITLE
usdcat/usdview does not print/display Prim properties according to 'properties' metadatum

### ISSUE THREAD

**Issue by syoyo** [PixarAnimationStudios/USD#2130]
### Description of Issue

Apprently USD library traverses/displays Prim properties alphabetically, not by the order specified in `properties` Prim metadatum
(On the contrary, Prim tree is traversed/displayed according to `primChildren` metadatum)

### Steps to Reproduce

```
#usda 1.0

def Sphere "world"
{
  double radius = 1.2
  double ev = 3.3
}

def Sphere "aworld"
{
  double radius = 2.0
}
```

And  `usdcat` and reorders the list of properties in "world" Prim  to

```
def Sphere "world"
{
    double ev = 3.3
    double radius = 1.2
}

def Sphere "aworld"
{
    double radius = 2
}
```

Situation is same for usdview

![image](https://user-images.githubusercontent.com/18676/206923481-7be8ebb5-22a6-4e4d-9925-d909b44998b4.png)

while the order of Prim tree is preserved("world" then "aworld".  `primChildren` Root layer(stage) metadatum is `["world", "aworld"]`)

If we encode this scene to USDC(`usdcat input.usda -o input.usdc`), `properties` Prim metadatum is encoded as

```
properties = ["radius", "ev"]
```

but `usdcat` and `usdview` ignores it.

Reordering properties become problematic when we want to take a diff of USD scenes in Ascii(e.g. through usddiff), manage USDA scene asset in version management software(e.g. git)

It'd be nice to traverse/display properties according to `properties` metadatum as done in `primChildren`

### System Information (OS, Hardware)

N/A

### Package Versions

22.11

### Build Flags

N/A

**Comment by spiffmon** [comment]
Hello @syoyo !
   While it may not be very well documented (though [with help we are working on that](https://github.com/PixarAnimationStudios/USD/pull/2126)), it is a deeply intentional behavior that both properties and metadata fields in both the UsdPrim/UsdProperty API's, **and** in the usda text format itself are always<sup>1</sup> lexicographically ordered, as defined by [TfDictionaryLessThan](https://graphics.pixar.com/usd/release/api/struct_tf_dictionary_less_than.html).  

One of several key reasons for this decision is, in our experience, precisely to make diffing files easier.  If all you are ever doing with usd is exporting files from non-native-usd apps, processing datastructures in a serial, deterministic fashion, this may not be obvious.  But consider a DCC that is built natively on USD, performing interactive edits in layers that start out with little or no data in them.  If I have a primitive with scalar rotation xformOps, and I use some direct manip handles to set the X rotation to 60 and the Y rotation to 45, should I get a different output file if I perform those manipulations in one order vs the other?  

We do not think of USD layers as "a history of how the scene was constructed" like a maya file is; instead each output format's layout is optimized for its intended workflows (in our pipeline, at least).  As you noted, we **do** pay attention in the Sdf data model itself (i.e. must be honored by **all** formats) to **prim creation ordering**.  This again was a pragmatic decision based on our experience using USD's precursor in Presto, where in rigging setups, the ordering of sibling prims has meaning for execution order, and is therefore highly intentional.  _Possibly_ prim creation order is more intentional in general, also...

If you can possibly conform your usda output to what you would get from the USD API's, I hope that you would not have as much problems with diffing and rc management?

<sup>1</sup> Properties on a UsdPrim **can be intentionally ordered** for purposes of retrieval/iteration by setting the metadata `propertyOrder` on the prim.  `propertyOrder` is an array of `token` representing property names... precisely how it is consumed by `UsdPrim::GetProperties()` et al is perhaps for a later presentation... but understand that it **only** affects composed prim/property presentation, not how properties will be serialized in a usda file.  Also, there is no such corresponding mechanism for ordering metadata.

**Comment by syoyo** [comment]
@spiffmon Thanks for the info!

> usda text format itself are always1 lexicographically ordered, as defined by [TfDictionaryLessThan](https://graphics.pixar.com/usd/release/api/struct_tf_dictionary_less_than.html).

>  Also, there is no such corresponding mechanism for ordering metadata.

Understand! So we need to keep in mind that USD lib exported USDA prints properties always lexicographically...


> If you can possibly conform your usda output to what you would get from the USD API's, I hope that you would not have as much problems with diffing and rc management?

There are usecases I want to add/remove properties, and/or modify property name(primvar names) of DCC(pxrUSD lib) exported USDA using text editor or scripts/regex tool without interacting USD API. Applying `usdcat` before taking a diff or version management would be a solution though.
