### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

### ISSUE THREAD

**Issue by hjoonpark** [PixarAnimationStudios/USD#2162]
### Description of Issue
Using Mac with M1, I can install USD and import it in python:

```
import pxr
from pxr import Usd

```
and writing/reading usd files works.

But when I try to usd `usdview`, this error comes up:
```
% usdview some.usd 
qt.core.plugin.loader: In /Users/username/miniforge3/plugins/platforms/libqwebgl.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/username/miniforge3/plugins/platforms/libqoffscreen.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/username/miniforge3/plugins/platforms/libqminimal.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/username/miniforge3/plugins/platforms/libqcocoa.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

I tried almost every solutions out there, starting from 

reinstalling conda env,

not even using conda,

re-installing opencv-headless,

installing qt5, qt6, qt@5, qt@6 using homebrew,

etc.

Can anyone tell me how to fix this?

**Comment by meshula** [comment]
I can't tell from your description if you are building USD via the build_usd.py script, or if you are configuring cmake manually versus your own dependencies.

homebrew does do it's own qt5 builds for M1, but that is not something that the Qt foundation supports, and it's not a tested pathway. If you are building USD with openimageio, a further problem is that homebrew causes further issues by bringing things into your build that you may not want, or that may conflict with the build. I'm not going to go into specifics here because homebrew supplied libraries continously change version, and anytihing I mention may well have changed by now. So, unless you need to get things working against homebrew supplied dependencies, I'd avoid that path as it's a lot of work to keep current with.

Note that USD does not have a dependency on opencv, but opencv does have a dependency on libraries that OpenImageIO uses, such as openexr. So there is a further versioning and configuration challenge, if you intend to rely on opencv to provide dependencies for OpenImageIO.

If this is your first time building USD, I would recommend using the build_scripts/build_usd.py script as your starting point, and once you've seen that working, then investigate integration with other packages like opencv and package managers like homebrew.

Whether you go for the scripted installation, or whether you pursue something more complex, a well tested pathway is to use  conda, and to first `pip install PySide6` within your active environment, and then you will also have to `conda install PyOpenGL` and possibly `jinja2`.

**Comment by hjoonpark** [comment]
I ended up reinstalling miniforge3 clean (it seems python 11 doesn't work so ended up using python 3.9 instead, and preinstalled `pip install PySide6`,  `conda install PyOpenGL`), and both usd, usdview works well now. I must have broken something midway.
Thanks

**Comment by meshula** [comment]
Awesome :) Python 3.10 will be supported in the upcoming 23.02 release, but Python 3.11 is still in the future.
