### ISSUE TITLE
`GetLocalToWorldTransform` doesn't convert the `upAxis` of a referenced file into the `upAxis` of the root file

### ISSUE THREAD

**Issue by expenses** [PixarAnimationStudios/USD#2188]
This issue sorta covers the same ground as https://github.com/PixarAnimationStudios/USD/issues/589.

### Description of Issue

Say I have this usd:
_a.usda_
```
#usda 1.0
(
    upAxis = "Y"
)

def Sphere "instanced" (
    references = @./b.usda@
) {}
```

that references this usd:
_b.usda_
```
#usda 1.0
(
    upAxis = "Z"
    defaultPrim = "sphere"
)

def Sphere "sphere" {
    double3 xformOp:translate = (0.0, 0.0, 1.0)
    uniform token[] xformOpOrder = ["xformOp:translate"]
}
```

You'd expect that this code would return `(0.0, 1.0, 0.0)` for the translation, but it instead returns the original `(0.0, 0.0, 1.0)` translation.
```cpp
pxr::UsdGeomXformCache cache;
auto transform = cache.GetLocalToWorldTransform(prim);
pxr::GfVec3d translation = transform.ExtractTranslation();
```

This is especially painful for using files authored in Blender, as it always sets `upAxis = "Z"`.

Is there something I should be doing instead to get the expected transform?

### System Information (OS, Hardware)
USD commit 59eaff4e29bd54b45c509f38dc294b9fcb7140f0

_Edit: changed some terminology to be clearer_

**Comment by sunyab** [comment]
Filed as internal issue #USD-7908

**Comment by spiffmon** [comment]
Hi @expenses , I could have sworn we discussed this recently, but I can't find any trace on usd-interest or gitHub (ah... maybe it was on ASWF slack?).  USD actually cannot reliably auto-compute the needed compensatory transformation for you at runtime because the needed data (stage metadata `upAxis` and `metersPerUnit`) in the *referenced* asset is not coposed into the scne, and so if you flatten the stage, it is just gone.  There are some other reasons, also...

Our guidance is for scene-assembly tools to add the needed compensatory transform on any prim on which you add a reference to another asset.  Given that you may need both a scale and a rotation to compensate for differences in both scene scale and orientation, it could definitely make sense to package that "AddCompensatingTransformation" logic into a UsdUtils function, and we'd be happy to consider a PR for one!

**Comment by expenses** [comment]
@spiffmon yep, I asked the question in the ASFW slack :) I'm pretty happy with that answer for now, adding a root node in blender isn't too hard and there's a planned feature for it to be added as an export option: https://developer.blender.org/tag/usd/. I'm going to close this.
