### ISSUE TITLE
Katana crash loading USD with material facesets

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#235]
### Description of Issue
If you export to USD a maya mesh that has two different component groups, both assigned to the same material, then when you try to import that USD into katana, katana will crash

### Steps to Reproduce
1. Unzip the attached file somewhere
2. Open `cube_material_faceSets_crash.ma` in maya
3. Export it to usd
4. In katana, create a pxrUsdIn, and point it at the created usd
5. Set your view node to your pxrUsdIn node, then expand the scene hierarchy until you can see the children of the cube node - it should crash

### System Information (OS, Hardware)
Linux

### Package Versions
usd-0.7.6

[cube_material_faceSets_crash.zip](https://github.com/PixarAnimationStudios/USD/files/1126547/cube_material_faceSets_crash.zip)

**Comment by spiffmon** [comment]
Hah. This points out a critical flaw in our face set encoding design. Because it uses a single relationship paired with the "array of sets in the partition", no two sets can share the same target. The question is how fundamental a redesign we need to pursue; we have already encountered some friction with MaterialX in our design. From a Luma perspective, do you think the Alembic-style encoding, with its own round tripping problems we tried to avoid, is a better overall model to pursue?

--SpiffiPhone

**Comment by chadrik** [comment]
We prohibit the use of face assignment (in this instance, an animator
slipped one by our relatively new USD export process) so our goal was
simply to get the code to a state where it would not crash if that happened
again.  I personally don't have an opinion on this but maybe @elrond79 does.

**Comment by elrond79** [comment]
I think this might just be a bug in the maya exporter, rather than a flaw in the design (at least as far as Maya material assignment is concerned).  ie, at an attribute level, Maya will happily let you assign two different component groups from the same shape to the same shading group... but I believe functionally it's equivalent to just having all the faces in one group.  So just changing the exporter to check for this case, and then combine the face sets, should be good.

**Comment by spiffmon** [comment]
Thanks, guys! I think we can make both Maya and katana plugins more robust.

--SpiffiPhone

**Comment by jtran56** [comment]
Filed as internal issue #148363.

**Comment by sunyab** [comment]
Cleaning up old issues, the Katana and Maya plugins have long been retired from the distribution.
