### ISSUE TITLE
how to build" boost_python27-vc142-mt-gd-x64-1_70.lib"

### ISSUE THREAD

**Issue by chongzijun123** [PixarAnimationStudios/USD#2375]
I use the vs2019 and USD23-02, I include the libs and the headers. but vs report can't open boost_python27-vc142-mt-gd-x64-1_70.lib, the libs only has the boost_python27-vc142-mt-x64-1_70.lib, How can I compile this? thanks.

**Comment by meshula** [comment]
The not-found library name is `boost_python27-vc142-mt-gd-x64-1_70.lib` which has a `-gd` in it. The `-gd` indicates a debug build of the library. Our build script doesn't build the debug versions of boost. Since vs is looking for the `-gd` version, I think you must be trying to build the `Debug` target, which isn't supported in USD 23.02. If you pick a different target to build such as `Release` or `RelWithDebInfo`, you should be able to build.

**Comment by chongzijun123** [comment]
thanks for your reply!

**Comment by sunyab** [comment]
Filed as internal issue #USD-8200

**Comment by FlorianZ** [comment]
If I understand correctly, this library dependency also pertains to python 2, which starting with 23.05 is no longer supported. Please, let me know if I am misreading, though!!
