### ISSUE TITLE
Setting instanceable flag changes primitive position in hydra viewport

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#2380]
### Description of Issue
Attached is a USDA file where the hydra viewer changes the apparent xform of a prim simply by virtue of toggling the instanceable flag on the prim.

### Steps to Reproduce
1. Open this file in usdview: [ref.zip](https://github.com/PixarAnimationStudios/USD/files/11171966/ref.zip)
2. In the Interpreter window, run `usdviewApi.stage.GetPrimAtPath('/reference/Instance0').SetInstanceable(True)`
3. Notice that the box in the viewport moves! The details view shows the bbox and xform of the USD prims haven't changed, but hydra must be doing something weird, or I am totally missing something. I think maybe the issue has to do with the non-uniform scales, because cases with simpler transforms I think don't have this behavior. But that's just a guess.
4. Toggling the instanceable flag moves the prim consistently between these two transforms.

### System Information (OS, Hardware)
Windows 11, using Houdini's USD build.

### Package Versions
Tested with USD 22.05 (houdini 19.5) and 21.08 (houdini 19.0)

**Comment by spiffmon** [comment]
That sounds plausible, @marktucker ... I wouldn't be surprised if we had no non-uniform scales in our tests... we'll check it out.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8215

**Comment by tgvarik** [comment]
The observed behavior is due to the constant primvar `primvars:scale` authored on `</reference/Instance0>`. This primvar has no meaning outside an instancing context. Once `</reference/Instance0>` becomes a native instance, that primvar suddenly has meaning.

This appears to be the natural consequence of several separate rules:
1) Constant primvars are inherited down the tree;
2) Native instances convert their constant primvars into instance-interpolated primvars at the Hydra instancer level; and
3) Hydra instancers can use primvars `primvars:rotate`, `primvars:scale`, `primvars:translate`, and `primvars:instanceTransform` to control instance transforms.

The usual means for setting a native instance's transform is through authoring a transform on it using `xformOp`s. You can't do that with point instancers, hence rule 3. Hydra instancers essentially lose the distinction between native and point instancing. So when the Hydra instancer sees the primvar, it applies it to the instance (after the instance's authored transform).

@marktucker: What is the expected effect of `primvar:scale`, authored where it is?

Here is a [minimal test scene](https://github.com/PixarAnimationStudios/USD/files/11468232/scale.txt) that removes the complex authored transforms and statically demonstrates the behavior. Rename .txt to .usda, github does not accept .usda files.

**Comment by marktucker** [comment]
Interesting... Thank you for the explanation, I never would have found that. I got this file from a user, so I don't really know why the scale primvar is there.

My gut reaction is that I wouldn't expect any of those primvars to have any effect on the transform of the instance. I can certainly understand the logic in the code that causes this to happen, but it really seems like an accidental side effect rather than something intentional. The mechanism is completely opaque on the USD side. These primvars don't affect the UsdGeomBBoxCache or UsdGeomXformCache (or any other xform related computations). So if I'm looking for overlapping bboxes, do I need to explicitly look for this case and manipulate the results coming out of those Cache objects?

If the Cache objects were updated, the asymmetry between instanced and non-instanced prims would still seem problematic to me. In your sample USD file, if I set primvars:translate on /World, only one of the three prims moves. Unless I toggle the instanceable flag on /World/NoInstance, in which case that prim moves. That just seems completely unexpected to me... But maybe that's just because I've never seen it before...

**Comment by tgvarik** [comment]
@marktucker Thanks for your patience. We've been discussing the best way to handle this.

These four primvar names have special meanings internal to Hydra and should not be used for any other purpose. The behaviors you're seeing are undesirable, so there isn't anything you should be doing to accommodate them. Unfortunately, these primvars are part of the contract between scene delegates and render delegates, so any change to them will be a breaking one that we'll need to do carefully to minimize disruption. We are hoping to be able to move these primvars into a separate, hydra-only namespace by 23.11, after which they'd be protected against collisions with custom primvars.

Until then, the workaround would unfortunately be to use a different name for the custom primvar.

Here again is the list of affected primvar names:

- `primvars:rotate`
- `primvars:scale`
- `primvars:translate`
- `primvars:instanceTransform`

**Comment by marktucker** [comment]
Thanks @tgvarik, that sounds great.  In the meantime it's easy for us to tweak a few settings in Houdini to at least make it difficult for users to accidentally author primvars with these names with our tools. And perhaps most importantly, we are now armed with this knowledge in case we get any more bug reports caused by this.

**Comment by tgvarik** [comment]
This change is in 23.11, see [this forum post](https://forum.aousd.org/t/hydra-synthesized-instancer-primvars-renamed-in-release-23-11/797) for details.
