### ISSUE TITLE
AMD Radeon 360 R7 - Shader problem - windows 10

### ISSUE THREAD

**Issue by cgrigstd** [PixarAnimationStudios/USD#2385]
### Steps to Reproduce
1. 

### System Information (OS, Hardware)
Windows 10
Radeon R7 360
### Package Versions
Version Radeon  22.6.1
### Build Flags
UsdView shader problem.

python 2.7, PyOpenGL 1.1, PySide 1.2

Shaders doesn't draw correctley.. Every shaders are draw with red color, render mode GL.
![usdview_shader_issue](https://user-images.githubusercontent.com/106169496/231841338-0fff877e-30ca-460e-80fb-3413a95ab869.PNG)

**Comment by sunyab** [comment]
Filed as internal issue #USD-8231

**Comment by davidgyu** [comment]
As documented in [VERSIONS.md](https://github.com/PixarAnimationStudios/USD/blob/dev/VERSIONS.md) we do our testing with Python3, PyOpenGL 3.x, and PySide2 or PySide6. So, it would be good to try updating your third party dependencies to see if that helps.

I can confirm that the current dev branch and v23.05 release candidates don't have this problem when running on Windows 10 w/ AMD 5600M, AMD 6800 XT, or AMD 7900 XTX or when running with recent NVIDIA or Intel GPUs.

Are you seeing any other errors? Since we don't have access to a system with your graphics card, I'm not sure how much additional help we can provide.

**Comment by cgrigstd** [comment]
I will try to compile with version 25.5
Where can I get v25.05?

I have no errors in the console. The error that I have told you about is only visual.
My card is out of fashion now.
but i have to faith that it can work haha 😁

Thanks for the help!

**Comment by davidgyu** [comment]
Apologies, I meant [USD v23.05](https://github.com/PixarAnimationStudios/USD/releases/tag/v23.05) which we tagged for release yesterday.

**Comment by cgrigstd** [comment]
mmm okay, I compiled the same version 😢

**Comment by cgrigstd** [comment]
Hi there!!

Now I'm have this error with v23.05 last release update

cmake --build . --config Release --target install -- /M:12

**Comment by cgrigstd** [comment]
Hi there!!

 v23.05 last release update
 
 Warning: in _AdapterLookup at line 279 of E:\USD\pxr\usdImaging\usdImaging\delegate.cpp -- Selected hydra renderer doesn't support prim type 'Material'


My cmake version is 3.26.3


PD: I have using environment dev with conda.

**Comment by dinelanthony** [comment]
Hi @cgrigstd did you ever resolve this issue? I have the same error message (although for a different reason) and was wondering if you might have found a way around it?

**Comment by davidgyu** [comment]
Are you still seeing these issues @cgrigstd or @dinelanthony?

I've been able to build and run the latest v24.03 release on the hardware and OS configurations listed in my first comment above and I'm still not seeing these issues.

**Comment by davidgyu** [comment]
Marking this closed based on our testing as described above.

Please open a new issue if this is still a problem for you. Thanks!
