### ISSUE TITLE
[Katana] Reloading layers causes issues with custom file format plugins

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#241]
### Description of Issue
When forcefully reloading layers in katana, the custom generates lots of warnings and in some cases crash.

We saw the same behavior using usdAbc, usdObj and partio_usd. Since usdAbc an usdObj are the de facto documentation for implementing custom file formats, I believe that this issue is not because of our incorrect code in partio_usd.

### Steps to Reproduce
1. Export a simple animated mesh (moving cube for example) to Alembic.
2. Reference that Alembic in an usd file, and bring it in a Katana scene using pxrUsdIn.
3. Expand the scene graph, so objects show up in the viewport.
4. Open a python console and type in the following commands
- from pxr import Sdf
- Sdf.Layer.ReloadLayers(Sdf.Layer.GetLoadedLayers())
5. Change frames back and forth.

You should see a bunch of warning messages showing up in the terminal. Like this
```Coding Error (secondary thread): in _GetOrCreateVisibilityQuery at line 232 of /ssd/rez-build/usd/dev/src/pxr/usd/lib/usdGeom/bboxCache.cpp -- Failed verification: ' attr ' -- Unable to get attribute 'Visibility' on prim at path </test>```

After investigating the problem a bit more, the error message comes from a failed attribute creation, after the schema has been created over the prim, and was validated.

For example, this leads to a crash in our partio format, source found here

https://github.com/LumaPictures/partio/tree/redpawfx-rez/contrib/partio4USD/fileFormat

Debugging the crash didn't lead to any possible solutions (besides doing an extra check in UsdAttributeQuery), so we are puzzled what's causing this.

### System Information (OS, Hardware)
Centos 7

### Package Versions
Latest commit from dev, and Katana 2.5v6.

### Build Flags
Release mode, no special flags added.

**Comment by jtran56** [comment]
Filed as internal issue #148782.

**Comment by spiffmon** [comment]
Hi Pal,

    I would expect badness from that sequence of actions, even from "core" 
file formats, potentially. UsdGeomBBoxCache and UsdGeomXformCache, by design, 
are not responsive to UsdNotice's. Therefore it is the client/user's 
responsibility to reset or blow all retained such caches when the stage 
changes.  Katana does not currently support incremental/sparse stage 
updating, and packs all of its "refreshing" logic into "Flush Caches", which 
I think basically does a reset on the pxrUsdIn op, which is the thing that 
holds onto BBox caches.

    So by manually calling ReloadLayers(), you have violated your warranty 
:-) and the BBox cache is using indexes into stale layer contents.  I could 
imagine this leading to memory corruption...

     Given that pxrUsdIn cannot recreate sparse subsets of its imported  
location hierarchy, I'm curious what you're trying to gain over what you 
would get by flushing caches when you know layers on disk have changed?

     That's what I think the problem is... are you able to reproduce this 
kind of error in usdview with custom file format plugins?  If you are, then 
we should try to get a repro, because usdview does flush its caches 
appropriately when doing "Reload All Layers", so should not trigger this theory.

Cheers,
--spiff

PS. The UsdGeom cache/computers are not responsive to scene edits because we 
wanted them to be lightweight and "simple".  Pretty epic fail on the latter 
criteria for BBoxCache, in spite of that, and we'd like to do a complete 
redesign, at some point, for threaded efficiency and possibly multi-frame 
caching.

**Comment by sirpalee** [comment]
No, the problem does not happen in usdview.

How can we get the caches flushed in pxrUsdIn?

**Comment by nxkb** [comment]
Hi spiff,
This is certainly a complex topic, so apologies if I'm glossing over some things. We've tried quite a few approaches now in order to get an up to date picture of the layers and stages without restarting katana. Some of the likelier approaches and results are the following:

- Katana's Flush Caches button: doesn't reload the layers so ends up using a stale layer from the global layer cache which is missing new edits that have been added since starting katana.
- Sdf.Layer.ReloadLayers(Sdf.Layer.GetLoadedLayers()) : causes the above badness
- Reload Layers and then Flush Caches: in my (perhaps hasty) end of day test, this still had the issues and warnings of Reload Layers. 

Would you expect that last method to work? Should we continue pursuing Reload Layers, but hunt down and clear some other caches in katana? We have not yet tried to replicate exactly how usdview is refreshing the layers, which looks to be carefully clearing caches and then reopening its stage. Is that the way to go?

Thanks!

**Comment by radon199** [comment]
Did anyone have results with reloading properly within Katana?

We still have issues where Katana sometimes will not update the scene graph until we close and open Katana again. Our resolver will say things are updated but that doesn’t happen in the viewport or scenegraph. Flushing the caches does not fix it.

**Comment by sunyab** [comment]
Closing out old issue, the Katana plugin has long been retired from the distribution.
