### ISSUE TITLE
Can not ComputeBoundMaterial properly When Instancing

### ISSUE THREAD

**Issue by wangxuming999** [PixarAnimationStudios/USD#2422]
### Description of Issue

Consider the following scene description.

```
def "table001"
{
    rel material:binding = </table001/materials/render/standardSurface1>

    over "geometry"
    {

        over "Table"
        {

        }
    }

    def "materials"
    {
        def "render" (
            prepend references = @../render/table001_render.v001.usd@
        )
        {
        }
    }

}
```

when ref this usd using following usd 

```
 def Xform "table001_inst001" (
    instanceable = false
    prepend references = @../asset/table_001.v001.usd@
)
{
    
}
```

I CAN get geometry binding material using 'UsdShadeMaterialBindingAPI(prim).ComputeBoundMaterial()'.

but when I set 'instanceable' True

```
 def Xform "table001_inst001" (
    instanceable = true
    prepend references = @../asset/table_001.v001.usd@
)
{
    
}
```
 I  use 'auto proto = prim.GetPrototype()' to get proto, then  iterate proto prims.
But Now I can NOT get geometry binding material using 'UsdShadeMaterialBindingAPI(prim).ComputeBoundMaterial()'.

besides, if I change referenced usd to

```
def "table001"
{
    #rel material:binding = </table001/materials/render/standardSurface1>
    over "geometry"
    {
        #change rel position
        rel material:binding = </table001/materials/render/standardSurface1>
        over "Table"
        {

        }
    }

    def "materials"
    {
        def "render" (
            prepend references = @../render/table001_render.v001.usd@
        )
        {
        }
    }

}
```

I CAN get geometry binding material using 'UsdShadeMaterialBindingAPI(prim).ComputeBoundMaterial()'.

### System Information (OS, Hardware)
Windows11 
### Package Versions
USD 19.11

**Comment by spiffmon** [comment]
Hi @wangxuming999 ,
   This is expected behavior, though not, I realize, well-documented.  In [the paragraph just below the table here](https://openusd.org/release/api/_usd__page__scenegraph_instancing.html#Usd_ScenegraphInstancing_Prototypes), we state:
> Prototype prims do not have metadata or properties, only children prims.

I will file an internal task to not only discuss the reasons for this at that point in the document, but also to think about how to make that important information more salient, and for us to think about "user level" documentation for instancing, even though I think you _are_ more concerned with the developer-level documentation.

This characteristic of prototype root-prims explains why your final construction, where you introduce an intermediate "geom" prim to contain the binding, **does** work as you expect.

Finally, I'll note that, as described [here](https://openusd.org/release/wp_usdshade.html#implication-on-renderer-instancing), it is **intended** that Materials can be bound **uniquely**, per-instance, even (using collection-based bindings and the "strongerThanDescendants" binding-strength) uniquely per-prim-within-the-prototype, that if you want to be fully correct in processing a UsdStage (and admittedly, Hydra is not yet correct in the case of collection-based per-instance assignment overrides) you will need to evaluate Material Bindings in the context of each instance.
