### ISSUE TITLE
Please add a DeepCopy method to Usd.Stage

### ISSUE THREAD

**Issue by OlegAlexander** [PixarAnimationStudios/USD#2449]
Hello and thank you for creating USD!

I would like to suggest adding a DeepCopy method to Usd.Stage for the purpose of creating pure functions in Python. I'm currently writing functions in a procedural style, like this:

```python
from pxr import Usd, UsdGeom, Sdf  # type: ignore[import]

def create_xform_procedural(stage: Usd.Stage, xform_path: str) -> None:
    UsdGeom.Xform.Define(stage, xform_path)
```

However, what I really want to do is rewrite this function in a functional programming style, like this:

```python
def create_xform_functional(stage: Usd.Stage, xform_path: str) -> Usd.Stage:
    stage_copy = stage.DeepCopy() 
    UsdGeom.Xform.Define(stage_copy, xform_path)
    return stage_copy
```

Or maybe create a decorator which will DeepCopy the stage for me, like this:
```python
@purify
def create_xform_functional(stage: Usd.Stage, xform_path: str) -> Usd.Stage:
    UsdGeom.Xform.Define(stage, xform_path)
    return stage
```

The only way that I've found to make a deep copy of the stage is to Export it to a temp file and Open it, like this:

```python
import tempfile

def deepcopy_stage(stage: Usd.Stage) -> Usd.Stage:
    temp_file = tempfile.gettempdir() + "/temp.usd"
    stage.Export(temp_file)
    stage_copy = Usd.Stage.Open(temp_file)
    stage_copy.Reload()
    return stage_copy
```

As you can imagine, I'm not happy with this solution at all because it's slow and hacky.

Would it be possible to add a DeepCopy method to Usd.Stage? And if not, is there another way to make a deep copy of a stage in memory? Thank you!

### System Information (OS, Hardware)
Python 3.10, Windows 11

### Package Versions
usd-core 23.5 https://pypi.org/project/usd-core/

**Comment by sunyab** [comment]
Filed as internal issue #USD-8365

**Comment by spiffmon** [comment]
Hi @OlegAlexander ... the idea of "deep copy" in USD is a bit fraught precisely because Usd objects (Stage, Prim, etc) are designed to share their "real data" from shared SdfLayers.  The idea of "Copy-on-write" UsdStages, with efficient sharing of underlying structures/work, though, is something that @sunyab experimented with several years ago, for a use-case very similar to yours.  That use-case went away, though, and we didn't want to refine the feature or take on the extra complexity it brought without a strong motivator.

So, lacking that, I can at least suggest two changes to your deepcopy_stage that should make it more efficient:
```python
def deepcopy_stage(stage: Usd.Stage) -> Usd.Stage:
    anonLayer = stage.Flatten()
    stage_copy = Usd.Stage.Open(anonLayer)
    return stage_copy
``` 

i.e.:
1. Leverage anonymous (in-memory) layers.  Because most "big data" in USD is stored in VtArrays, and they are copy-on-write, the memory overhead of making numerous copies of the stage and its data should be less than you'd think.
2. There's no need to `Reload()` the sage after opening it, in either case.  Though it will also be mostly a no-op...

We're not likely to revisit the copy-on-write prototype anytime soon, as things stand.  Would you be OK closing this out for now?

**Comment by OlegAlexander** [comment]
Dear @spiffmon, your function is exactly what I was looking for! I've tested it and it works perfectly.

For anyone who comes across this in the future, here is my test:

```python
from pxr import Usd, UsdGeom  # type: ignore[import]


def deepcopy_stage(stage: Usd.Stage) -> Usd.Stage:
    return Usd.Stage.Open(stage.Flatten(addSourceFileComment=False))


def create_xform_functional(stage: Usd.Stage, xform_path: str) -> Usd.Stage:
    stage_copy = deepcopy_stage(stage) 
    UsdGeom.Xform.Define(stage_copy, xform_path)
    return stage_copy


if __name__ == '__main__':
    stage1 = Usd.Stage.CreateInMemory()
    stage1 = create_xform_functional(stage1, '/World/Xform1')
    print(stage1.ExportToString())

    stage2 = deepcopy_stage(stage1)
    stage2 = create_xform_functional(stage2, '/World/Xform2')
    print(stage2.ExportToString())
```

Which prints:

```console
#usda 1.0
(
    doc = """Generated from Composed Stage of root layer
"""
)

def "World"
{
    def Xform "Xform1"
    {
    }
}


#usda 1.0
(
    doc = """Generated from Composed Stage of root layer
"""
)

def "World"
{
    def Xform "Xform1"
    {
    }

    def Xform "Xform2"
    {
    }
}
```

Notice that I set `addSourceFileComment=False` so that the doc string isn't duplicated every time a copy is made.

Thank you very much @spiffmon and @sunyab!
