### ISSUE TITLE
STL containers in C++ public interface

### ISSUE THREAD

**Issue by DanilAndreev** [PixarAnimationStudios/USD#2470]
Hi.
I have a question about USD C++ interface. I've notices that USD supports only shared library build. Also I've noticed that public interface uses STL containers as bridge arguments and there is no options to disable this behaviour in build scripts. 
As I know STL containers memory layout differs depending on configuration and build tools.

So the question is: why do you use this approach and what can you advise how to avoid problem with different implementations of STL containers.

**Comment by spiffmon** [comment]
Hi @DanilAndreev , although the build_usd.py script does not expose it as an option (because boost python cannot be made to work with the static library approach, IIRC), [the underlying cmake setup does support building USD static libraries](https://github.com/search?q=repo%3APixarAnimationStudios%2FUSD%20PXR_STATIC_LIBS&type=code).

Common practice in the VFX world from which USD originated, and our advice, is to build USD with the same compiler that the application into which you will be linking it will be built.

**Comment by DanilAndreev** [comment]
@spiffmon thanks for your answer. Just to be sure I want to specify: If I want to create, for example, Houdini plugin that uses USD it is common practice to embed self-compiled USD dlls in my package instead of using Houdini's USD dlls?

**Comment by marktucker** [comment]
If you're making a Houdini plugin, you should build your plugin against the USD library that ships with Houdini (and you should use the compiler options that Houdini use to build USD, which are documented, or you can use the hcustom command to help you figure out what compiler options to use). If you include your own USD build with your Houdini plugin, your USD libraries will conflict with Houdini's USD libraries and Houdini will most likely crash.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8401

**Comment by spiffmon** [comment]
CLosing for now, please reopen if the advice given is insufficient, @DanilAndreev !
