### ISSUE TITLE
Path to using external/system copies of OpenEXRCore and libdeflate?

### ISSUE THREAD

**Issue by musicinmybrain** [PixarAnimationStudios/USD#2619]
### Description of Issue

Beginning in release 23.08, USD bundles a copy of OpenEXRCore 3.2.0, along with a copy of libdeflate 1.18.

Is this a permanent situation, or is there a path to supporting system copies of these libraries again at some point?

This query is required by Fedora Linux policy: https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

### Steps to Reproduce
1. Examine https://github.com/PixarAnimationStudios/OpenUSD/tree/v23.08/pxr/imaging/hio/OpenEXR.

### System Information (OS, Hardware)

N/A

### Package Versions

23.08

### Build Flags

N/A

**Comment by meshula** [comment]
Hi, thanks for the question.

There is no intention to support system copies of libdeflate or OpenEXRCore, as allowing users to substitute their own versions of these libraries is not intended.

In support of that, and in order to be good neighbours ~ 

- libdeflate is copied strictly in support of the copy of OpenEXRCore
- the libdeflate copy has been incorporated such that it's symbols are hidden and should not conflict with usage of system libdeflate. The linkage is further restricted to be within the specific Hio.so dynamic library, without republication. Hio itself does not use libdeflate, so it is unaffected by the existence or non-existence of system libdeflate.
- OpenEXRCore is not simply a copy of distributed OpenEXRCore. It has slight internal modifications to meet the needs of the USD project. Attempting to elide OpenEXRCore and substitute a system library would result in incorrect functionality.
- The libdeflate symbols are only visible to the OpenEXRCore integration.
- OpenEXRCore itself has been similarly modified such that no symbols are exported for visibility beyond internal usage within the Hio dynamic library, and as such should not interfere with end users' need to utilize system OpenEXRCore.

I hope this information helps you in resolving the questions raised by https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8618

**Comment by musicinmybrain** [comment]
Thanks for the quick and detailed follow-up!
