### ISSUE TITLE
FileFormat plugin double extension

### ISSUE THREAD

**Issue by antopilo** [PixarAnimationStudios/USD#2635]
It is currently not possible to specify a double extension for a fileFormat plugin.

For example: `test.mpcdi.xml`

It would be useful for different file formats as using .xml in this example would prevent from having another file format ending with xml.

Thank you

**Comment by spiffmon** [comment]
Hi @antopilo ,
   Supporting that fully generally and automatically would be problematic for parts of our codebase, and likely others' as well.  **However**, you should absolutely be able to do this for yourself.  As @gitamohr just reminded me, ArResolver allows you to override the GetExtension() logic that SdfFIleFormat uses to determine an asset's extension, and there are no restrictions (IIRC) on what the declared extension in the FileFOrmat's plugInfo.json can be.  Since you are writing code/plugins already for your formats, you should be able to either override the DefaultResolver, or create one or more tiny "URI resolvers" to handle this extension management in your pipeline?

Please close this if you agree that solves the issue, or let us know why it doesn't!

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8639

**Comment by spiffmon** [comment]
Closing - please reopen if our suggestion did not work - thanks!
