### ISSUE TITLE
Script build fail during boost build

### ISSUE THREAD

**Issue by col-one** [PixarAnimationStudios/USD#270]
### Description of Issue
In a clean environement with devellopement command prompt when you run python USD\build_scripts\build_usd.py "C:\users\do\USD"
I have an error during boost build : 
 ERROR: Failed to run 'b2 --prefix="C:\users\do\USD" --build-dir="C:\users\do\USD\build" -j4 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-date_time --with-filesystem --with-program_options --with-python --with-regex --with-system --with-thread toolset=msvc-14.0 install'

### Steps to Reproduce
1. run python USD\build_scripts\build_usd.py "C:\users\do\USD"
2. wait few minutes

### System Information (OS, Hardware)
windows 10. VS 2017

**Comment by jtran56** [comment]
Filed as internal issue #150172.

**Comment by sunyab** [comment]
Hi @col-one, the error message should have mentioned a log file to check for errors. Could you attach that file here? I think it should be in C:\users\do\USD\src\boost_1_61_0. Thanks!

**Comment by col-one** [comment]
[log.txt](https://github.com/PixarAnimationStudios/USD/files/1250468/log.txt)
Sure ! here it is. Thanks

**Comment by sunyab** [comment]
> C:\users\do\USD\build\boost\bin.v2\libs\atomic\build\msvc-14.0\release\address-model-64\threading-multi\lockpool.obj
> : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'

This looks like a relevant error from the log. This might be due to trying to use the x86 MSVC toolset to try to build USD, which requires the x64 toolset. How did you launch the development command prompt? If you have a shortcut titled "x64 Native Tools Command Prompt for VS 2017", can you try to run the build script using that command prompt instead? Also note that cmake >= 3.8 may be required due to this issue:

https://stackoverflow.com/questions/42730478/version-numbers-for-visual-studio-2017-boost-and-cmake

We likely need to update our docs to provide better instructions for launching the right command prompt. Let us know how this goes!

**Comment by col-one** [comment]
Ok thanks it's work, and you can precise that python27 64bits is needed. I have an other compilation probleme during jpeg, i will do an other issue.
