### ISSUE TITLE
[Feature] Please allow specified handed coordinate along with upAxis

### ISSUE THREAD

**Issue by Thaina** [PixarAnimationStudios/USD#2723]
### Description of Issue

Since there are various system that use difference style of axis, such as unity and unreal. In the same reason as `upAxis` parameter be specified to amend the up vector for some application like blender. Please allow more axis parameter as optional value for usd file

This also allow conversion between left-handed/right-handed coordinate system. And so it would more efficient and convenient for any application to export it's object as in their native coordinate, And to the target application may or may not need to convert, since they might use the same native coordinate system. And thus the USD would be really universal and efficient

And so I propose

```usd
#usda 1.1
(
   upAxis = "Y"
   forward = "Z"
   handed = "L" // "L" or "R"
)
```

If not specified, the default value will be right-handed coordinate with Y up, which is default of USD

Alternatively, we might specified `+/-` along with `X|Y|Z`

```usd
#usda 1.1-2
(
   upAxis = "+Y"
   forward = "+Z" // can be omitted
   rightAxis = "+X" // default -X
)
```

This above describe unity axis

As for Unreal

```usd
#usda 1.1-2
(
   upAxis = "+Z"
   forward = "+X"
   rightAxis = "+Y"
)
```

As for Blender

```usd
#usda 1.1-2
(
   upAxis = "+Z"
   forward = "+Y"
   rightAxis = "+X"
)
```

and many other system. godot, Maya, etc

```usd
#usda 1.1-2
(
   upAxis = "+Y"
   forward = "-Z"
   rightAxis = "+X"
)
```

Or even the 2D ui system

```usd
#usda 1.1-2
(
   upAxis = "-Y"
   forward = "-Z" // many UI system are pile up, such as material design. More value of depth means it piling upward into camera
   rightAxis = "+X"
)
```

Also maybe this value could actually be optionally encoded with one `axis` value, replaceable exclusively

```usd
#usda 1.1-2
(
   axis = "+Y+Z+X" // UP - Forward - Right
)
```

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8752

**Comment by spiffmon** [comment]
Hi @Thaina , thank you for the thoughtful analysis.  The problem here, which we've seen in similar instances before, is that there is a strong tension between making USD cater to all possible encodings, and the complexity we push onto all clients, increasing the likelihood that many of them will get things wrong.

I'd invite you to bring this topic to the ASWF USD user group or slack channels, but I'm going to close this for now because even simply allowing a choice between Z and Y up is already a sometime source of confusion in the USD ecosystem.

**Comment by Thaina** [comment]
@spiffmon Thank you for your response

First, I would like to ask, how can I access `ASWF USD user group` ?

Also I think github issue is the best place to discuss anything, forum is unlike chat and it easier to threading and searching

Lastly, I think at least for the coordinate system. We should have standard conversion tool written in C that manage the conversion of USD from any coordinate to any coordinate

I would like to argue that this is the same process that all client need to cope with when their native coordinate are not the same as USD anyway. But if there is universal converter integrated in universal file format, it would actually lessen the complexity in the long run

**Comment by drwave** [comment]
Here’s a link to join the ASWF slack:

https://join.slack.com/t/academysoftwarefdn/shared_invite/zt-2geymi1f9-ltk7CSR07s3vrfhqpNmB6A￼

**Comment by spiffmon** [comment]
It's a really challenging problem, and we're not sure USD is in a position to authoritatively dictate a solution - or that it even _can_.  @jcowles wrote [a really excellent blog post on the problem](https://towardsdatascience.com/change-of-basis-3909ef4bed43), one conclusion of which was "you need to convert everything".  But when you get to including primvars into consideration, I'm not sure it's always clear what "everything" is, since some primvars are spatial, some aren't, and we don't always know which it is.

Injecting a negative scale into a hierarchy is likely going to be problematic for imported data, and baking the change of basis into all points, etc is a big transformation of the data.  If the community wants to discuss this on [the AOUSD forum](https://forum.aousd.org/c/community/usd/7), we're definitely open to it!

**Comment by Thaina** [comment]
I see your point about primevar. However that was also a problem in itself too that the format need to convert anyway if the native coordinate of the app are not the same. Even without freedom of coordinate, each app need to know which primvar data is spatial and need to be handled

Maybe this also need to include spatial marker to primvar datapoint? such as in cascading or querying style
