### ISSUE TITLE
Use Boost 1.82 for Python 3.11

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2741]
USD can't build for Python 3.11 due to older Boost version usage. 

We should use Boost 1.82 when detecting Python 3.11 or higher in accordance with VFX Platform 2023

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8842

**Comment by ze897c** [comment]
Folks, sorry for comment out of the blue. I am hacking (badly) build_usd.py to build for 3.11 for various reasons. On OSX I was able to change boost to 83 & build/run (mostly) just fine. Tried same on my ubuntu box: boost built (as yet untested) but thier is an issue building USD. Some digging leads to error with `sysconfig`. Call to `sysconfig.get_config_var("LDLIBRARY")` gives, 'libpython3.11.a', which does not exist. `sysconfig.get_makefile_filename()` gives `<path-to-conda-env>/lib/python3.11/config-3.11-x86_64-linux-gnu/Makefile' and the (auto-generated) Maklefile is wrong (LDLIBRARY=      libpython$(VERSION)$(ABIFLAGS).a).

This is just FYI/heads-up, and a note to keep me in-looped.

Thanks for the libs, all!

**Comment by sunyab** [comment]
Hi @ze897c, which version of Ubuntu are you running? And what method did you use to install Python 3 -- did you go through `apt` or are you using `conda` or some other package manager?

**Comment by ze897c** [comment]
Hello,Installed 3.11 through conda, while creating a new env. ubuntu```bash$ lsb_release -aNo LSB modules are available.Distributor ID:	UbuntuDescription:	Ubuntu 20.04.6 LTSRelease:	20.04Codename:	focal```Cheers,XeateOn Oct 24, 2023, at 12:08 PM, Sunya Boonyatera ***@***.***> wrote:Hi @ze897c, which version of Ubuntu are you running? And what method did you use to install Python 3 -- did you go through apt or are you using conda or some other package manager?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by nvmkuruc** [comment]
@dgovil This seems like it's been addressed.  Do you think we can close?
