### ISSUE TITLE
Fail compile during OIIO 

### ISSUE THREAD

**Issue by col-one** [PixarAnimationStudios/USD#294]
### Description of Issue
Hello, i am back. In a classic build, compile fail during OIIO build.
pthread doesn't find.
`
Build FAILED.
"C:\Users\DO\build_usd\build\oiio-Release-1.7.14\CMakeFiles\CMakeTmp\cmTC_2adb9.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  C:\Users\DO\build_usd\build\oiio-Release-1.7.14\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\DO\build_usd\build\oiio-Release-1.7.14\CMakeFiles\CMakeTmp\cmTC_2adb9.vcxproj]
    0 Warning(s)
    1 Error(s)
`
Thanks a lot !

### Steps to Reproduce
1. run python script build
2. wait the oiio build.

### System Information (OS, Hardware)
windows 10 , vs2017

**Comment by sunyab** [comment]
Hi again @col-one, could you post the full log.txt from C:\Users\DO\build_usd\build\oiio-Release-1.7.14? Thanks!

**Comment by jtran56** [comment]
Filed as internal issue #151610.

**Comment by col-one** [comment]
[log.txt](https://github.com/PixarAnimationStudios/USD/files/1345734/log.txt)
And thanks again ! =]

**Comment by meshula** [comment]
It says it couldn't find boost, so the build must have failed much earlier in the process.

**Comment by col-one** [comment]
hum thanks for this point, but i am a bit in the trouble : 
`Boost include path: C:/Users/DO/build_usd/include/boost-1_61

  Could not find the following Boost libraries:

          boost_filesystem
          boost_regex
          boost_system
          boost_thread`

My path C:/Users/DO/build_usd/include/boost-1_61 include well a boost directory. Would I set BOOST_ROOT var ?

**Comment by meshula** [comment]
Can you check if this directory -

  c:/users/DO/build_usd/lib/

has the required boost lib and dlls? They should be named boost_filesystem-vc140-mt-1_61.dll and boost_filesystem-vc140-mt-1_61.lib, etc.

**Comment by col-one** [comment]
Yes. they're here. Would it be a solution to copy them ?

**Comment by meshula** [comment]
I don't think copying them is the right thing. If I'm not mistaken, the build script is telling the OIIO build where to find them. At this point I'll have to defer to Sunya in case he has any suggestions on how to proceed.

**Comment by sunyab** [comment]
Sorry for the delay. I think there are two issues here:

1. The build script uses boost 1.61 on Windows, which doesn't support Visual Studio 2017. The build script tries to apply some patches to let it work anyway, but it looks like we're missing some additional patches that are required. We'll try to figure out the best approach to fix this. 

In the meantime, one workaround you can try is to modify build_usd.py to download a newer version of boost that does support VS2017. You can look for BOOST_URL in the script and change:

BOOST_URL = "http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz"
to
BOOST_URL = "http://downloads.sourceforge.net/project/boost/boost/1.64.0/boost_1_64_0.tar.gz"

Then re-run the build script, making sure to point it to a different directory. I haven't had a chance to try this out yet, so I'd love to hear if this works out for you.

2. The build script isn't smart enough about trying to rebuild dependencies when they fail the first time around. My guess is that you ran the build script and the boost build failed, then you ran it again and the script skipped over boost. That's why you're hitting the boost error much later. 

We need to fix the build script to be smarter about this. Right now, it assumes that if a boost header exists in the include directory, the build must have been successful. However, this isn't the case; boost will partially install headers even if it runs into errors later on.

Sorry for all the issues you're running into with this, @col-one! We'll get this squared away.

**Comment by meshula** [comment]
One more thing to check is cmake version. I had to upgrade to at least 3.8.2 to deal with 2017.

**Comment by cspears2002** [comment]
Is this the same issue I have been having?

https://groups.google.com/forum/?hl=en#!topic/usd-interest/636SFc0nUtM

**Comment by sunyab** [comment]
Hi @cspears2002, it's unclear whether you're having the same issue. So far, the primary issue here has been due to using Visual Studio 2017, and since you're using 2015 my guess is you're running into something else.

Note that the log in the first post and the log you posted are from cmake trying to figure out if your system has pthread.h. Those errors are expected and don't indicate what's actually wrong with the OpenImageIO build. We'd need to see the log.txt file in build\oiio-Release-1.7.14 to get more information.

**Comment by cspears2002** [comment]
Ah okay.  Sorry.  I’ll locate the log and start a new issue.  Thanks!

**Comment by robthebloke** [comment]
One problem I encountered when I moved to boost 1.64.0 is that it has a bug in the build script. See this issue here: https://github.com/boostorg/build/issues/194
See the comment from andrejnau from Apr 27. Replacing the build script will fix that issue.

**Comment by sunyab** [comment]
Thanks @robthebloke! I ran into the same issue while testing out a fix for the build script. Here's what I've discovered so far:

- boost 1.64 was the first version that claimed support for VS2017, but doesn't work out of the box because of that boost python bug. We could either try to manually patch up that version in the build script or use 1.65, which was released in early September.

- However, support for boost 1.65 was only added in cmake 3.9.3, so users would need to install that version or later.

At the moment, I'm considering having the build script use 1.65 and checking for the appropriate cmake version if it detects we're using VS2017, but I'm open to suggestions if anyone has alternatives.

**Comment by meshula** [comment]
There's no way around requiring cmake 3.9.3 I think.

Here is a patch to the build script that allows building USD with VS2017. Note that I upgraded the OIIO version in order to have a version without a gazillion warnings in it.

```
diff --git a/build_scripts/build_usd.py b/build_scripts/build_usd.py
index a55b759..78496f7 100644
--- a/build_scripts/build_usd.py
+++ b/build_scripts/build_usd.py
@@ -363,14 +363,14 @@ def InstallZlib(context, force):
         RunCMake(context, force)
 
 ZLIB = Dependency("zlib", InstallZlib, "include/zlib.h")
-        
+
 ############################################################
 # boost
 
 if Linux():
     BOOST_URL = "http://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.gz"
 elif Windows() or MacOS():
-    BOOST_URL = "http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz"
+    BOOST_URL = "http://downloads.sourceforge.net/project/boost/boost/1.65.0/boost_1_65_0.tar.gz"
 
 def InstallBoost(context, force):
     with CurrentWorkingDirectory(DownloadURL(BOOST_URL, context, force)):
@@ -401,19 +401,19 @@ def InstallBoost(context, force):
             b2_settings.append("-a")
 
         if Windows():
-            b2_settings.append("toolset=msvc-14.0")
-            
-            # Boost 1.61 doesn't support Visual Studio 2017.  If that's what 
-            # we're using then patch the project-config.jam file to hack in 
-            # support. We'll get a lot of messages about an unknown compiler 
+            b2_settings.append("toolset=msvc-14.1")
+
+            # Boost 1.61 doesn't support Visual Studio 2017.  If that's what
+            # we're using then patch the project-config.jam file to hack in
+            # support. We'll get a lot of messages about an unknown compiler
             # version but it will build.
             msvcCompilerAndVersion = GetVisualStudioCompilerAndVersion()
             if msvcCompilerAndVersion:
                 compiler, version = msvcCompilerAndVersion
                 if version >= MSVC_2017_COMPILER_VERSION:
                     PatchFile('project-config.jam',
-                              [('using msvc', 
-                                'using msvc : 14.0 : "{compiler}"'
+                              [('using msvc',
+                                'using msvc : 14.1 : "{compiler}"'
                                 .format(compiler=compiler))])
 
         if MacOS():
@@ -425,12 +425,12 @@ def InstallBoost(context, force):
         Run('{b2} {options} install'
             .format(b2=b2, options=" ".join(b2_settings)))
 
# The default installation of boost on Windows puts headers in a versioned 
# subdirectory, which we have to account for here. In theory, specifying 
# "layout=system" would make the Windows install match Linux/MacOS, but that 
# The default installation of boost on Windows puts headers in a versioned
# subdirectory, which we have to account for here. In theory, specifying
# "layout=system" would make the Windows install match Linux/MacOS, but that
# causes problems for other dependencies that look for boost.
 if Windows():
-    BOOST = Dependency("boost", InstallBoost, "include/boost-1_61/boost/version.hpp")
+    BOOST = Dependency("boost", InstallBoost, "include/boost-1_65/boost/version.hpp")
 else:
     BOOST = Dependency("boost", InstallBoost, "include/boost/version.hpp")
 
@@ -640,11 +640,13 @@ PTEX = Dependency("Ptex", InstallPtex, "include/PtexVersion.h")
 ############################################################
 # OpenImageIO
 
-OIIO_URL = "https://github.com/OpenImageIO/oiio/archive/Release-1.7.14.zip"
+OIIO_URL = "https://github.com/OpenImageIO/oiio/archive/Release-1.8.5.zip"
 
 def InstallOpenImageIO(context, force):
     with CurrentWorkingDirectory(DownloadURL(OIIO_URL, context, force)):
-        extraArgs = ['-DOIIO_BUILD_TOOLS=OFF',
+        extraArgs = ['-DBOOST_LIBRARYDIR="' + os.path.join(context.instDir, 'lib') + '"',
+                     '-DBoost_COMPILER=-vc141',
+                     '-DOIIO_BUILD_TOOLS=OFF',
                      '-DOIIO_BUILD_TESTS=OFF',
                      '-DSTOP_ON_WARNING=OFF']
 
@@ -904,16 +906,25 @@ group.add_argument("-q", "--quiet", action="store_const", const=0,
 
 group = parser.add_argument_group(title="Build Options")
 group.add_argument("--build", type=str,
-                   help=("Build directory for USD and 3rd-party dependencies " 
+                   help=("Build directory for USD and 3rd-party dependencies "
                          "(default: <install_dir>/build)"))
-group.add_argument("--generator", type=str,
-                   help=("CMake generator to use when building libraries with "
-                         "cmake"))
+
+if Windows():
+    # note - forcing this generator as it is hard coded throughout this script
+    # and is painfully easy to mess up as a command line parameter!
+    group.add_argument("--generator", type=str,
+                       default='-G "Visual Studio 15 2017 Win64"',
+                       help=("CMake generator to use when building libraries with "
+                             "cmake"))
+else:
+    group.add_argument("--generator", type=str,
+                    help=("CMake generator to use when building libraries with "
+                            "cmake"))
 
 (SHARED_LIBS, MONOLITHIC_LIB) = (0, 1)
 subgroup = group.add_mutually_exclusive_group()
 subgroup.add_argument("--build-shared", dest="build_type",
-                      action="store_const", const=SHARED_LIBS, 
+                      action="store_const", const=SHARED_LIBS,
                       default=SHARED_LIBS,
                       help="Build individual shared libraries (default)")
 subgroup.add_argument("--build-monolithic", dest="build_type",


```

**Comment by nicelifeBS** [comment]
Thanks @meshula,
your changes made it build on my windows machine with VS2017. One thing which I needed to add for boost was the LIB env var to the python libs directory.

Cheers

**Comment by Anti-Distinctlyminty** [comment]
@meshula I had to change 
```+    group.add_argument("--generator", type=str,
+                       default='-G "Visual Studio 15 2017 Win64"',
+                       help=("CMake generator to use when building libraries with "
+                             "cmake"))```

to

```+    group.add_argument("--generator", type=str,
+                       default='Visual Studio 15 2017 Win64',
+                       help=("CMake generator to use when building libraries with "
+                             "cmake"))
```

**Comment by lumonix** [comment]
FWIW,
On top of the above fixes to the build script, I also had to manually install the 64bit pre-compile version of boost 1.65 and move its 'lib64-msvc-14.1' to 'C:\Program Files\USD\src\boost_1_65_0/lib/'.

After that the build script managed to build ImageIO.

**Comment by sunyab** [comment]
Hi all,

The latest USD release (18.09) added better support for Visual Studio 2017 to build_usd.py. In particular, under VS2017 the script will now use boost 1.65.1.The CMake version requirement for VS2017 was bumped to 3.12 as well. We haven't changed the OpenImageIO version, as the build passed through with the current version being used.

With these changes, I'm able to run build_usd.py to completion on a fresh VM with Windows 10 and VS2017, including OpenImageIO.  I'm going to close this issue out as resolved. If you're still running into issues building with VS2017, please file a new issue with your relevant build info. Thanks!
