### ISSUE TITLE
Using OpenEXR and stb image from inside the USD repository is a potential source of ODR violations

### ISSUE THREAD

**Issue by dlarsson-adobe** [PixarAnimationStudios/USD#2948]
### Description of Issue
The USD source code comes with its own version of OpenEXR and stb image.
In the event you integrate USD in an application bringing in those dependencies themselves of a different version you are likely to get undefined behavior and crashes.

Ideally third parties should be externalized so they can be provided by a parent project instead of assuming USD needs its own version.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
Historically Linux and MacOS are more prone to these things

### Package Versions
N/A

### Build Flags
N/A

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9297

**Comment by meshula** [comment]
Hi, we don't use untouched versions of stbi, nor of OpenEXRCore (nor of libdeflate which is a dependency of OpenEXRCore). We don't use the OpenEXR library itself beyond the OpenEXRCore C library.

We have declared all the symbols to be static and so the symbols do not escape Hio, and the headers themselves are not exported nor visible outside of the Hio library.

The only way I can think of to generate an ODR problem is to modify Hio to link in some way to another copy of stbi or another copy of OpenEXRCore. Potentially, if you contrived to statically link all of an application and statically link OpenUSD you could hit an ODR problem, but then you are also engineering around other issues, such as Hydra's dynamic plugin loading behavior, so that scenario is already requiring special attention. The monolithic static build we provide itself is dynamically loaded even though the OpenUSD libraries themselves are statically linked into it; so in that supported case, the symbols wouldn't conflict with an application because they're not exported transitively.

It's not intended that users be able to substitute their own stbi or OpenEXRCore, because we want the behavior of Hio relative to those two libraries to be deterministic across platforms and build environments, which wouldn't be the case if end users could change them.

I hope this explanation gives you confidence that you can use your own copy of OpenEXR and stbi in your application without issue. If there's a scenario that doesn't line up with all of this where the symbols could escape and cause an ODR violation, please help get me on the same page :)

**Comment by FlorianZ** [comment]
Closing this given @meshula 's description above, but @dlarsson-adobe, please feel free to reopen if you think there is still an issue here. Thank you!
