### ISSUE TITLE
animated shader parameter resolves incorrectly when using 60 timeCodesPerSecond - always uses 24, giving wrong answer

### ISSUE THREAD

**Issue by drwave** [PixarAnimationStudios/USD#2958]
I'm uploading a zip - here's the README that explains the issue:

This directory contains two top-level USD files, the only difference being that one has **24** **framesPerSecond** and **timeCodesPerSecond**, while the other has **60** **framesPerSecond** and **timeCodesPerSecond**.

Other than that, they have the same:
- start/end timeCodes (1 & 60, respectively)
- mesh that has the same material bound to it

That material has a texture which changes every integer time code to point at a different jpg file that has that number as a picture. This material is in the file **DiffuseMaterial__NumbersCard.usd**, and the JPG images are in the images subdirectory.

One would expect that both would show the same images as you monontonically increase the time code, the only difference that one would last for 1 second of playback (60/60) and the other would be 2.5 seconds (60/24).

Unfortunately, that is not what happens.

For the file **OneToSixty_60.usd**, as the timecode increases in usdview, the corresponding timecode that is used to look up which texture file to use lags behind by 24/60 amount, so by the time the timecode reads 60 in usdview, it's only showing the texture "24" (see enclosed screenshot).

For the file **OneToSixty_60.usd**, as the timecode increases in usdview, the corresponding timecode that is used to look up which texture file to stays in step with the timecode, so by the time the timecode reads 60 in usdview, it's showing the texture "60" (see other screenshot).

[OneToSixtyBug.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/14320527/OneToSixtyBug.zip)

**Comment by spiffmon** [comment]
@drwave , can you confirm whether this seems to be **only** a problem with mapping time to texture filenames, or whether it is problematic for any animated attribute?

**Comment by drwave** [comment]
This seems to be true for other parameters like `emissiveColor`. 

If I change the emissive value after the first 24 timeCodes from red to green, and then again after 48 to blue, it looks correct (i.e. the texture is 60 and tinted blue) for the 24 tc/sec one, and incorrect (red tint and 24) for the 60 tc/sec one.

I've modified the material file in the previous zip to have this information - you can drop it in the same dir and run usdview on each file to see the result. I have included screenshots of each.

[DiffuseMaterial__NumbersCard.usd.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/14324912/DiffuseMaterial__N
![OneToSixty_24Emissive](https://github.com/PixarAnimationStudios/OpenUSD/assets/1679418/15714947-be7f-4c16-a4e2-3f312d1299ec)
![OneToSixty_60Emissive](https://github.com/PixarAnimationStudios/OpenUSD/assets/1679418/42beaa99-4554-4dbb-97ee-0af5feb0185f)
umbersCard.usd.zip)

**Comment by drwave** [comment]
This is what I added:

```
 color3f inputs:emissiveColor.timeSamples = {
        1: (1, 0, 0),
        24: (1, 0, 0),
        25: (0, 1, 0),
        48: (0, 1, 0),        
        49: (0, 0, 1),                
        }

```

**Comment by drwave** [comment]
One other bread crumb that might be interesting/useful:

I noticed this issue because I was texture mapping some 60 fps footage onto a mesh of 256x192 faces, but I was also using the average color of a downsampled 256x192 image to assign a displayColor to each face.

It was the fact that those two didn't match as I toggled between Display->Enable Scene Materials on and off that I realized the issue.

The animated displayColor is correct.

**Comment by drwave** [comment]
If you want a sample of that, I can upload it.

**Comment by BigRoy** [comment]
Shouldn't the `DiffuseMaterial__NumbersCard.usd` file also author `timeCodesPerSecond`? Since it has no opinion authored I believe it's considered to be at default `timeCodesPerSecond = 24` and `framesPerSecond = 24`. Likely won't solve the issue though?

Even though not exactly the same "issue" as [here](https://github.com/Autodesk/maya-usd/issues/3580#issuecomment-1932638687) I just wanted to cross-reference it because it might be useful as example files to showcase the same issue. Since it's also about referencing other files with different FPS or timecodes and the frame ranges mismatching.

And if this reported issue here is "intended behavior" and the [USD Survival Guide does not explain it well](https://lucascheller.github.io/VFX-UsdSurvivalGuide/core/elements/animation.html#animationMetadata) it might be worth adding more details there so the behavior is clarified. Or of course, update any official docs if they are also lacking - which they might be. The "timecode" section [here](https://openusd.org/dev/api/_usd__page__properties_of_scene_description.html#Usd_ValueResolution) appears empty?

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9327

**Comment by drwave** [comment]
@BigRoy My understanding is that the top level layer is the only metadata that matters for the stage, and that's the file you load, which sets both of those explicitly (one to 24, the other to 60).

**Comment by drwave** [comment]
Hmm, my understanding seems to be wrong @BigRoy . If I have a specific version of the material for each of the 24 and 60 cases, it works as expected.

Now I'm not sure if that's a bug, or I just was wrong about precedence.

**Comment by spiffmon** [comment]
@BigRoy is correct, @drwave ... `timeCodesPerSecond` is considered **composition data** that is specified per-layer, and the engine uses it to add an "extra" time-mapping (applying also anfy layerOffset that appears on the `subLayers` or `references` that brings the layer in).  This is the only way to honor the artistic intent of the authored data in a layer... without it we're (and we were initially, until we fixed it six or so years ago) in the same hell that we currently are with `upAxis` and `metersPerSecond`.  Since time is part of the core Sdf schema/concerns, we were able to make the engine take care of it for you.  Geometrical concerns are schema-level, so there's no way we can compensate in the engine.

Does that mean this is not a bug?  Btw, there _may_ be an hgiMetal issue to follow up on... @meshula demonstrated some behavior with your scene on a Mac where even if you disable "Enable Scene Materials", the texture way still being displayed in some form.  That should not be the case.  Without scene materials, we should just be seeing a flat polygon, and that's what we'd see in OpenGL, I claim.

**Comment by drwave** [comment]
Thanks @spiffmon - TIL!
Yes, it's not a bug. 
And the thing that @meshula demonstrated is just me mapping the displayColor to the same info that the Material is pulling from, but because the geometry is in a different layer (that does have the timeCodesPerSecond) it's working as expected. So I will close this out - not a bug.
