### ISSUE TITLE
Windows Py3.11 issue with OpenGL in USDView

### ISSUE THREAD

**Issue by jonassorgenfrei** [PixarAnimationStudios/USD#2996]
Hey 

i tried building the latest USD [v24.03] with Python 3.11.2
It builds fine and i can use the library.
But the scene viewer in USDView stays black.
![8c29f3be31a6aad3886a3ff4b1297b0173555074_2_1035x571](https://github.com/PixarAnimationStudios/OpenUSD/assets/34287983/8046b15a-7dc0-40b1-9060-6c68a5889bdc)

I build with Python3.10 and this works. 

see: https://forum.aousd.org/t/usdview-black-screen/1307/5

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9413

**Comment by BigRoy** [comment]
Aside of the black screen do you get any errors or warnings reported in the console or command line that might hint to what is going on?

**Comment by jonassorgenfrei** [comment]
Hey @BigRoy 

unfortunatly there was no error shown in the terminal. 
Is there any debug flag i can use with usdview to may be force more info to be shown?

**Comment by jonassorgenfrei** [comment]
I think the most interesting thing is that it tries to open the programm twice. 
I added a screen capture of running usd view:

https://github.com/PixarAnimationStudios/OpenUSD/assets/34287983/77b68d4a-67b6-41d7-a2c7-c7f882f1cf73

**Comment by BigRoy** [comment]
> I think the most interesting thing is that it tries to open the programm twice. I added a screen capture of running usd view:
> 2024-03-12.12-25-26.mp4

That's interesting indeed - could you run `where python` in the cmd prompt to double check whether it's picking up the python you expect it to.

Also, could you show the contents of the `..\install_default\bin` folder?

---

You could try launching with [the `--traceToFile` (and maybe `--traceFormat`) argument to see if that points you to anything](https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usdImaging/usdviewq/__init__.py#L191-L207). Maybe it reports anything useful.

---

Not sure how polluted your `PATH` and `PYTHONPATH` env is - but if there might be conflicts with something else on your system it might be worth trying to prepend the new values instead of appending to those variables so they are preferred over anything pre-existing. So end with e.g. `;%PATH%` instead of starting with `%PATH%;`.

**Comment by jonassorgenfrei** [comment]
Just double checked that the correct python is executed this works well (i think otherwise my boost compile would complain).
![grafik](https://github.com/PixarAnimationStudios/OpenUSD/assets/34287983/fe1add6d-14fc-4cc7-9400-146e22b0bd35)

Tried with Preprending the path unfortunatly the same result.

Here's the trace i got from running the application:
[test.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/14571644/test.txt)


Here with tracePython
[test.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/14571728/test.txt)

**Comment by BigRoy** [comment]
Thanks for the details - I'll leave this to someone more knowledgeable this area.
