### ISSUE TITLE
Cannot `Sdf.CopySpec` relationship without targets to relationship with targets in crate layers

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#3095]
### Description of Issue
When `Sdf.CopySpec` is run with the following conditions
a) on a crate layer
b) with a relationship without a target as a source
c) and a relationship with a target as the destination, 

`TF_VERIFY` fails with the following error.
```
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_24__pxrReserved__::_ProcessChildren' at line 153 in file copyUtils.cpp : 'Failed verification: ' oldDstChildrenValue.IsHolding<ChildrenVector>() ''
```

Change any of the above conditions (ie. use `usda` instead of `usdc`), and the `Sdf.CopySpec` will succeed.

@roggiezhang-nv traced this back to divergent behaviors for how `targetChildren` is handled in the crate vs. text file formats.  The text file format returns a `VtValue` with a valid type that is non-empty.  The crate file format returns an empty `VtValue`.

We'd recommend making the text file format and crate behave the same way, and we're happy to contribute a fix if that's the agreed upon best approach. An alternative fix we considered is whether or not `Sdf.CopySpec` should be more permissive and filter out empty `VtValue`s, but that might be riskier.

### Steps to Reproduce
1. Create a file `copyrel.usda` with the following contents
```
def "target" {}

def "source" {
   rel myrel
}

def "dest" {
   rel myrel = </target>
}
```
2. Run `usdcat copyrel.usda -o copyrel.usdc`
3. Run the following python snippet
```
from pxr import Sdf

text = Sdf.Layer.FindOrOpen("./copyrel.usda")
Sdf.CopySpec(text, '/source', text, '/dest')

crate = Sdf.Layer.FindOrOpen("./copyrel.usdc")
Sdf.CopySpec(crate, '/source', crate, '/dest')
```

Note `Sdf.CopySpec` works for `usda` but not for `usdc` for the same content.

### System Information (OS, Hardware)
Linux

### Package Versions
24.05

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9703

**Comment by gitamohr** [comment]
> We'd recommend making the text file format and crate behave the same way, and we're happy to contribute a fix if that's the agreed upon best approach.

Thanks for the great report! I completely agree that consistency is key and I'd be happy to take a PR, cheers!

**Comment by roggiezhang-nv** [comment]
@gitamohr Hello, Alex. After more investigation, I found the issue was rooted from how targetChildren is treated for the underlying storage of usda (SdfData) and usdc (CrateData). I want to ask if that's the intension. 

Should targetPaths and targetChildren be synced with each other always? So updating targetPaths field will update targetChildren accordingly? Also, query targetChildren will return the same value list as targetPaths? I see CrateData for usdc has special treatment to all APIs when it's to set/get targetPaths/targetChildren so they will be consistent always. However, SdfData for usda doesn't, that means updating targetPaths will not update targetChildren afterwards. And this is the root cause why SdfCopySpec fails the test above. This issue is not only applied to targetPaths/targetChildren, but also connectionPaths/connectionChildren.

Also, SdfCopySpec has issues that it fetches all value/children fields to copy firstly, including targetChildren. Then it copies value fields. Lastly, it copies children fields. During the step of copying value fields, the targetPaths is cleared in the above example. That means targetChildren field is cleared also for usdc since it shares the same value as targetPaths, but not for usda as usda stores targetChildren separately. So it fails for the last step to copy children fields as the targetChildren field of that property is holding a null value now for usdc format. 

To fix this issue, we need to do one or both of the following steps:
1. Fix SdfCopySpec by moving the code to fetch children fields to the place after copying value fields so it could get a list of updated children fields as children fields may be changed during value fields copy.
2. Fix SdfData for usda so updating targetPaths/connectionPaths will update targetChildren/connectionChildren accordingly. 

I am not sure we need to fix 2 as targetChildren/connectionChildren is not used anywhere except in the Sdf internal. I want to hear from your ideas, thanks.

**Comment by roggiezhang-nv** [comment]
I created a PR here: https://github.com/PixarAnimationStudios/OpenUSD/pull/3117 to adopt fixes only to SdfCopySpec.

**Comment by nvmkuruc** [comment]
Closing-- Fixed with https://github.com/PixarAnimationStudios/OpenUSD/commit/26edc870e63cec57281dcc5f9c0e25ae66c50f04
