### ISSUE TITLE
How should we consider a doubleSided attribute specified as a varying one?

### ISSUE THREAD

**Issue by MootoolsSoftware** [PixarAnimationStudios/USD#3127]
### Description of Issue
The model downloaded from [https://openusd.org/release/dl_city_set.html](url) specifies a varying doubleSided attribute which is [not conform to the spec](https://github.com/PixarAnimationStudios/OpenUSD/blob/2864f3d04f396432f22ec5d6928fc37d34bb4c90/pxr/usd/usdGeom/schema.usda#L623).

The question is about the strategy to choose when such situation occurs.
Should be file being reject or the attribute interpreted as an uniform one?

**Comment by spiffmon** [comment]
Thank you for reporting this issue - this asset was created in very early days for USD, when our tooling was still evolving, and this issue escaped our notice.  Partly because _currently_ no part of the "data ingestion to rendering" from UsdStage to Hydra actually pays attention to an attribute's variability.

But you are correct that such a file should be considered to contain some invalid data, and we are now finally building and deploying a core validation framework that should be able to identify and report the error.  We will use this Issue to both fix the asset, and to implement a validator that catches such mistakes.

Now the tricky part... while `tinyusdz` is correct to identify a problem, what it (or any other) software should do about it is a more open-ended question.  We tend to take a "let's report any error we do find while opening and processing an asset, but continue as best we can" approach.  Which in the case of a "incorrectly typed/formed attribute" might be to continue as if the attribute were not authored at all.  That is not anything we prescribe, but to @syoyo san I might suggest there is a difference between "a usda file is so mangled that it cannot be parsed" and "an attribute-spec is well-formed, but does not conform to the schema specification", but again, that's his call!

**Comment by MootoolsSoftware** [comment]
Thanks for your explanations and clarifications

**Comment by MootoolsSoftware** [comment]
Thanks for your explanations and clarifications

**Comment by syoyo** [comment]
@spiffmon Thanks! So at the moment there seems no consensus how to handle the case when `varying` attribute is specified(authored) where `uniform` is expected in the schema. 

> Which in the case of a "incorrectly typed/formed attribute" might be to continue as if the attribute were not authored at all

I think this could introduce some confusion. For example, if USD have `bool doubleSided = true`, but ignoring it will set `doubleSided`  false(default fallback value).  

Thus, until the validation framework is provided, to avoid confusion, I'd like to be in strictly accordance with the schema(report variability/type mismatch Attribute as an error )
