### ISSUE TITLE
Bad bounds exported from Maya

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#326]
### Description of Issue
Not all geometry is encapsulated in the bounds.

### Steps to Reproduce
1. Export the attached scene from Maya
2. Look at it in usdview

[simpleScene.zip](https://github.com/PixarAnimationStudios/USD/files/1467678/simpleScene.zip)

![image](https://user-images.githubusercontent.com/1510114/32738022-83f06fba-c850-11e7-81c9-34d286d1303e.png)

### System Information (OS, Hardware)
Windows

### Package Versions
0.8.1

**Comment by spiffmon** [comment]
The problem here is you have meshes parented under meshes, which should be a validation error. For sure the exporter should be complaining, or doing something smarter (assuming the Maya file has three shapes under a common xform?)

--SpiffiPhone

**Comment by jtran56** [comment]
Filed as internal issue #153729.

**Comment by jcowles** [comment]
I actually don't have a working Maya plugin, but in my first comment I attached the maya scene that generated the file (in the zip file).

**Comment by mattyjams** [comment]
Hey Jeremy!

I think this may actually have been fixed already by @sirpalee in a5632644c3cad0dc18ab7b539878e01958434d97. That change should be in v0.8.2. Could you give this another try using that version when you get a chance?

As Spiff pointed out, due to the transform/shape collapsing that the Maya exporter is doing, the resulting USD ends up with meshes directly below other meshes. The change above fixes the issue by detecting when that is the case and **not** collapsing the transform and shape in that case.

When I export your test scene now, I get a prim hierarchy where only the leaf-level mesh "pSphere2" is collapsed. The other two meshes end up parented under their respective transforms, and the bounds look much more sensible in usdview.

[simpleScene_v0.8.2.zip](https://github.com/PixarAnimationStudios/USD/files/1607801/simpleScene_v0.8.2.zip)

**Comment by mattyjams** [comment]
Hey again Jeremy!

I'm going to close this issue out, as it should no longer be a problem, but feel free to re-open if you run into any more trouble here.

Thanks!


-Matt

**Comment by jcowles** [comment]
Sounds good!
