### ISSUE TITLE
[usdAbc]some bugs report and some features require

### ISSUE THREAD

**Issue by iceprincefounder** [PixarAnimationStudios/USD#360]
### Description of Issue
Hi there,

Bugs 1:
I tired USD-v0.8.2 usdAbc plug-in and it did not work at this version,the error log print like this:
```
Traceback (most recent call last):

  File "/home/xukai/Git/git_repo/usd/USD-v082/bin/usdcat", line 201, in <module>
    sys.exit(main())

  File "/home/xukai/Git/git_repo/usd/USD-v082/bin/usdcat", line 141, in main
    if not Usd.Stage.IsSupportedFile(inputFile):
pxr.Tf.ErrorException: 

	Error in 'pxrInternal_v0_8__pxrReserved__::PlugPlugin::_Load' at line 283 in file /home/xukai/Git/git_repox/USD/pxr/base/lib/plug/plugin.cpp : 'Load of '/home/xukai/Git/git_repo/usd/USD-v082/plugin/usd/usdAbc.so' for 'usdAbc' failed: /home/xukai/Git/git_repo/usd/USD-v082/plugin/usd/usdAbc.so: undefined symbol: _ZN7Alembic7AbcGeom2v811XformSample5addOpENS1_7XformOpERKN5Imath8Matrix44IdEE'
[
```
Bugs 2:
If we use "usdcat" to translate the alembic file which has multiple uvSets,the other usSets would lost only left the default.

Feature require:
We actually used USD to organize our scenes,but for some reasons,we have to export alembic model and animation files from maya and than translate to "usdc",we want to use "usdcat" to do this but there is a problem that "usdcat" would "Merge Transform and Shapes Nodes" by default and it seems that there is no option to change this,could you add a "usdcat" tools option or is there any other way?

I do know that usd has more great performance than alembic but we can not leave alembic by now,usdAbc is great to make it adapt to our pipe.

Thank you very much.

### Steps to Reproduce
1.usdcat ./alembicUV.abc -o ./alembicUV.usd

### System Information (OS, Hardware)
centos 6.7

### Package Versions
USD-v0.8.2

### Build Flags
[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/1585693/CMakeCache.txt)

Kevin Tsui

**Comment by spiffmon** [comment]
Hi Kevin,
**Linking Bug**
    My only thought on the build/link problem is that _maybe_ you are getting some mixing of versions/installations.  Could you try building 0.8.2 on a machine with no previous versions of USD or Alembic installed?  

**Multiple Alembic uvsets**
    We are not Alembic experts, and we added the conversions we could glean.  We specifically look for the primary _uv_ property on ISubdiv and IPolyMesh schemas.  We also convert the _arbGeom_ compound into UsdGeom primvars, and we hoped any other uvsets would be recorded in _arbGeom_ .
    If that's not so, we need to know where to look.  It would be very helpful if you could attach a simple Alembic file we could abcecho to see the name and location of secondary uvsets.  If secondary uv's **are** in _arbGeom_, then we have a problem with our arbGeom converter.

**Translating unflattened transform properties**
   I have been wondering how long it would be before someone requested this.  Currently, as you noted, we only attempt to translate the flattened transformation in our Abc reader.  Our pxrUsdIn Katana importer also flattens the transforms it reads from USD, so there's a double-whammy.  The AbcGeom component transform encoding is a bit more complicated than the UsdGeom encoding, and it would be preferable to have someone with Alembic expertise tackle the abc-to-usd translation - we'd be happy to advise on question about our usdAbc plugin, of course.

   It might be useful to ask about this in the usd-interest forum, as it's possible some other studio has had the same need as you, and already coded a solution?

Cheers,
--spiff

**Comment by spiffmon** [comment]
Sorry, I missed one of your questions, regarding the merging of xform and shape primitives... there is currently no way to disable this behavior.  I think it could be added, controlled by an environment variable, as we currently provide three environment variables that control how we translate alembic instancing into USD instancing.

Could I ask why this is problematic? Is it because you do look-dev using the Alembic namespace, and the bindings fall off when you import USD?  If so, could you tell us the authoring and consuming apps for the shading, and the delivery format?

--spiff

**Comment by iceprincefounder** [comment]
Hi Sebastian,
Glad to get your reply again,thanks.

For the "Linking Bug",yes just as you said,I tried to re-build it and have fixed it.

For the "Multiple Alembic uvsets",I have attached alembic and usd files with same uvSets and hope that helpful.By the way,we read USD files which have multiple uvSets with PxrUsdIn node in Katana and it\`s uv data is different than the data which read with Alembic_In node,that cost a problem:we could set parameter "PrimVar ST" in "PxrManifold2D" node and prman could read those uvSets,but the other renderer like arnold could not recognise them,only the default "st" set could be read.The Alembic_In node would parse uv data as a float list "index" and a point2 list "indexedValue" but the PxrUsdIn node would parse it as a only one point2 list "value",but every point`s uv index are wrote at usdPrims indeed.
[simple_uvsets.tar.gz](https://github.com/PixarAnimationStudios/USD/files/1588710/simple_uvsets.tar.gz)

For the "Translating unflattened transform properties",we don\`t merge xform and shape when we export model assets from maya because we need to make sure that we have the same scenegraph locations both in maya and katana,also,when we do look-dev in katana and export klf(katana look file) files,we have to make sure the same scenegraph location too.We could write a katana op node to solve this but it will be very convenient if you could add a option to usdcat tools,I don`t know if is it easy to make it :-)

Thanks again.

Kevin Tsui

**Comment by spiffmon** [comment]
Hi Kevin,
   Thanks much for the wonderful example files!  I can definitely see the problem, and the example files will be great for unit tests.  It looks like our alembic translator is using the getExpanded() method to attempt to "flatten" the uv sets (and any other arbGeom properties), but it isn't working as expected.  I believe that if you use usdedit on the result of "usdcat simple_alembic_uvsets.abc" and change the names of the properties like "primvars:testUV_1:vals" to simply "primvars:testUV_1" then you'll get a successful import in Katana that both prman and Arnold can use?

   We'll see if, while fixing this, we can preserve the indexing during translation, as at affects interpolation for facevarying quantities.

   Can you also please confirm that the problem with xform and shape nodes exists only for assets you have **already shaded** ?  That is, if you were building a new asset, from scratch, and you exported the geometry from Maya **with** xform+shape merged into a single Gprim in USD, then brought that geometry into Katana for lookdev, you would not have any pipeline problems, since klf's are not interchangeable with any other application, so there's no problem that it doesn't match Maya's namespace?

--spiff

**Comment by chadrik** [comment]
Hi Kevin,
From a pipeline perspective, I can understand the appeal of using existing
code to export alembic components and then glue them together using USD for
layouts and variants, however, I think this will ultimately cause you a lot
of headaches.  There are a handful of reasons to avoid usdAbc:
1) Anecdotally speaking, there don't seem to be many studios using it, or
at least few who are able/willing to submit fixes for it, as I've seen many
more issues created than pull requests.  The result is that quite a few
issues remain and progress on the plugin has been slow. At Luma we use it
only for converting assets from other vendors, or delivery to other
vendors, and it seems like every time we use it we hit a snag similar to
this one.
3) Performance is poor compared to USD crate files (this has been discussed
several times on usd-interest).

Ultimately, we decided that the amount of time saved on the pipeline side
by reusing our alembic export code would be lost chasing down bugs like
these, as well as missing out on a number of great features of USD at the
component level.  Of course, if you have the resources to fix the plugin,
then by all means do so (I'm sure it will be greatly appreciated!) but just
be aware that this is unlikely to be the last issue like this that you will
run into.

At this point the usdMaya exporter is a pretty solid replacement for
AbcExport (once the rest of our PRs merged, which should be soon), so my
recommendation would be to go that route.  If you're exporting from apps
other than Maya and Houdini, then sadly Alembic will still be necessary
(for now).

**Comment by iceprincefounder** [comment]
Hi Sebastian ,
Thanks for your workaround on the uvSets problem,I will have a try.For the problem about merging xform and shape,actually we do use the usdMaya exporter but when converting abc to usd,we have to open maya but that is no a big deal,we will consider chadrik\`s suggestion and also thank you @chadrik for your detailed suggestion.
