### ISSUE TITLE
Creating visual project or bff when building for Windows

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#525]
### Description of Issue
Is it possible to create vcxproj or bff when building for Windows?

**Comment by jtran56** [comment]
Filed as internal issue #161681.

**Comment by ix-dcourtois** [comment]
Hi, USD is a standard CMake project, so yes, just use a Visual Studio generator.
And if you build using the build_usd.py helper script, it's already using a Visual Studio generator so you can already find a solution file in the build folder.

Also for help, you might want to go there https://groups.google.com/forum/#!forum/usd-interest instead of filling an issue here :)

**Comment by c64kernal** [comment]
@ix-dcourtois is totally right about CMake being the way we generate Visual Studio projects.
