### ISSUE TITLE
Whether one UsdPrim's corresponding class is derived from another Prim? 

### ISSUE THREAD

**Issue by TongkuiSu** [PixarAnimationStudios/USD#537]
For an UsdPrim whose type is "mesh", it would   generate an class `UsdGeomMesh` inherited from `UsdGeomXformable`. My question is how can we get the corresponding class type with "mesh" or can we use the string "mesh" directly to decide whether it inherits from `UsdGeomXformable` or not?

**Comment by drwave** [comment]
Are you asking for Python or C++? If C++, if you have a UsdPrim prim, you could just write:

if (prim.IsA<UsdGeomMesh>()) {
  UsdGeomMesh meshPrim = UsdGeomMesh(prim);
  // do stuff with your meshPrim...

**Comment by superfunc** [comment]
For C++, it is `prim.IsA<UsdGeomMesh>()`.  For Python you pass the class name: `prim.IsA(UsdGeom.Mesh)`

**Comment by spitzak** [comment]
I think the question is that he has a string that *might* be
"UsdGeomXformable" but possibly some other class, and wants a way to turn
the string into a class.

**Comment by spiffmon** [comment]
The short answer is that there is no public method for robustly testing prim.IsA from a type string.  We have the underpinnings we need to do so, which is to look up the TfType corresponding to the given string, since TfType is what we use internally to answer the IsA question.  We have resisted doing so since the start of the project because we don't want to encourage people to be referring to schemas by string names, because the point of schemas is to make code more robust (compiler verifiable), and strings aren't.

The halfway point I think we'd consider is exposing an IsA that accepted a TfType.  Can you explain where you're getting the string "UsdGeomXformable" from?  If we provided a UsdPrim::GetTfType() method, would it be possible for your code to pass around TfTypes rather than strings?

**Comment by TongkuiSu** [comment]
Thanks. As mentioned by @drwave , we can use IsA() to do this, like `prim->IsA<UsdGeomXformable>()`, But in my project, I can't use it directly. What I can do is call another function and in this function call `IsA`, the problem is my argument is a string "UsdGeomXformable" , how can I convert it to class `UsdGeomXformable`? (just like @spitzak mentioned).  If I can get the prim's corresponding class type, that is also useful.

**Comment by superfunc** [comment]
Agreed with @spiffmon . Note that this is possible from Python currently.


(Python)
```
p.IsA(Tf.Type.FindByName('UsdGeomXformable'))
```

**Comment by TongkuiSu** [comment]
em, not supported in C++?(mine is C++)

**Comment by superfunc** [comment]
@TongkuiSu I don't think so, the python wrapping in `pxr/usd/lib/usd/wrapPrim.cpp` relies on a private function on `UsdPrim`, which could be exposed, as @spiffmon alluded to.
