### ISSUE TITLE
How to identify point light and spot light

### ISSUE THREAD

**Issue by TongkuiSu** [PixarAnimationStudios/USD#584]
As we know, there are point light and spot light in UE4. In USD, we can treat `UsdLuxSphereLight` as point light. but for spot light, I use  `UsdLuxSphereLight` + `UsdLuxShapingAPI ` to represent. Am I right? If so, a problem comes, in usd, both are `SphereLight`, how to determine the light type? Just through the inner parameter such as `shaping:cone:angle` and `shaping:cone:softness `?

**Comment by spiffmon** [comment]
That's what I would recommend.  We are transitioning code over to make use
of the new ability to "Apply" API schemas, so that you can do simply:
prim.HasAPI<UsdLuxShapingAPI>(), and the UsdMaya light export adheres to
the new discipline of using UsdLuxShapingAPI::Apply().

And just to be redundant/explicit, only SphereLight's that have the
*treatAsPoint* attr authored to true should be considered point or spot
lights.

--spiff

**Comment by TongkuiSu** [comment]
Thanks. Your response is always in time an helpful to me. I am working on Holodeck in nvidia and we use USD as the exchange between DCCs and game engines.

**Comment by spiffmon** [comment]
There is certainly precedence in UsdLux for non-physical controls, and it
looks like Unity also supports attenuation radius, though neither Maya nor
Houdini seem to.  Probably the thing to do here is just add an attribute
that is documented as only pertaining to the point-light approximation...
but the schema-wonk in me wants to at least consider replacing
treatAsPointLight with a PointLightAPI schema.  Let us think about it a bit?

--spiff

**Comment by wi1k1n** [comment]
Hi, was there any movement regarding the above mentioned PointLightAPI?
