### ISSUE TITLE
Wrong dependencies list on README.md

### ISSUE THREAD

**Issue by sayduck-daniel** [PixarAnimationStudios/USD#642]
While trying to install USD for the first time in order to programmatically create USDZ on an Amazon Linux 2 distribution I found some mismatch between your README.md and what is actually needed.

1. It was my fault but I misunderstood the fact USD will install the dependencies for me once a run the script. So I tried to install them manually before executing your script. Actually while doing, I saw you have the wrong versions on your README:

    - for `OpenSubdiv` the required version is `3.0.5` but installs `3.1.1`
    - for `GLEW` required version is `1.10.0` but installs `2.0.0`
    - for `OpenImageIO` the required version is `1.5.11` but installs `1.7.14`
    - for `Ptex` the required version is `2.0.30` but installs `2.1.28`
    - for `OpenShadingLanguage` the required version is `1.5.12` but does install
    - These libraries aren't mentioned but installed: `JPEG`, `TIFF`, and `PNG`

1. Some requirements missing

    - `GLFW` is required (otherwise I couldn't move forward with the build script) but not mentioned. `GLFW` requires `cmake` version `>= 3.0.0` and `USD` requires `cmake` version `2.8.8`

**Comment by jtran56** [comment]
Filed as internal issue #USD-4807.

**Comment by sayduck-daniel** [comment]
If somehow has the same problem and reads this, I can say after many hours trying all possibilities the following:

- You don't need imagin or usdview to create USDZ files. Just call it with --no-imaging and --no-usdview. This will only fetch TBB and Boost.

- Only GLFW is required to compile with USDVIew and Imaging.

- GLFW will require you to have cmake version 3.0 or higher.

- In case you use USDView, you need to have pyside and pyopengl.

- PySide requires cmake as well and will compile from source (this takes a while)

**Comment by sunyab** [comment]
Hi @sayduck-daniel, thanks for the feedback! We're looking at ways to simplify the docs and to true up the versions we have listed to avoid some of the confusion you ran into. Just a few notes for anyone following along:

- The versions we have listed in the README.md aren't exact requirements, later versions of those libraries are usually OK. The build script downloads newer versions for a variety of reasons, e.g. because they have fixes that make them easier to build.

- JPEG, TIFF, and PNG are only needed to build OpenImageIO, which is why the build script installs those libraries. However, USD itself doesn't need those libraries, and we don't want to list any transitive dependencies in our documentation.

**Comment by sunyab** [comment]
Since this issue was filed we've added a VERSIONS.md file that lists the dependencies we build and test against internally and use in build_usd.py We took a pass in the 20.05 release to true this list up to reflect the VFX Reference Platform CY2018. So I'm going to close this out. Thanks!
