### ISSUE TITLE
Mute/unmute behavior is inconsistent for UsdStage and SdfLayer

### ISSUE THREAD

**Issue by roggiezhang-nv** [PixarAnimationStudios/USD#676]
### Description of Issue
There are two ways to mute/unmute a layer: one is from UsdStage class and the other is from SdfLayer. However, the two ways does not send out the same notice (Stage will send out objectsChanged notice, but SdfLayer will send out global notice), which is confused. So it's better to keep them consistent.

### Package Versions
[0.8.5a]

**Comment by jtran56** [comment]
Filed as internal issue #USD-4863.

**Comment by roggiezhang-nv** [comment]
Just curious if this is improved after more than 1 and half a year. :)

**Comment by spiffmon** [comment]
Hi @roggiezhang-nv  - apologies for the radio silence here.  We haven't been creating USD authoring workflows internally that rely on managing layer muting, which is why this hasn't really gotten any attention.  We do agree that notifying when layer muting changes is valuable, as should be other stage state-changes like load/unload, population-mask changes, and stage interpolation mode.   We'll try to get the layer-muting notification scheduled in the near future - thanks for your patience!

--spiff
