### ISSUE TITLE
1GB inputs to usdzip generate 2GB usdz file

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#686]
### Description of Issue
Subject says it all.

### Steps to Reproduce
1. Localize files into a directory
2. cd into the directory
3. run "usdzip Volund.usdz ."

First problem, usdzip attempts to zip the temp usdz file:
usdzip Volund.usdz .
Skipping empty file '.\Volund.vhdmao'.

When complete, the generated usdz file is 2GB, but the source files are 1GB total.
Let me know if you want my actual source files.

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD 18.11

### Build Flags
--openimageio --alembic

**Comment by drwave** [comment]
Sounds like an awesomely pathological alignment bug...

**Comment by jcowles** [comment]
Here's the full source:
https://drive.google.com/file/d/1LKpTCtulCfXXolYO4tNVQ8gPUTW3S955/view?usp=sharing

**Comment by spiffmon** [comment]
This was due to duplicate archiving, which is fixed in our dev tree, and I
believe was the result of commit 9bfcf499715c7b08fabff99959e38e83d7ab20d1 .

Jeremy I'd like to note that your give usdzip command-line won't produce a
legit usdz archive... when not using the "--asset" or "--arkitAsset" flags,
you must provide the root/default usd file as the *first *file following
the usdz file.  I successfully made an archive like so:

 usdzip Volund.usdz VolundModel.usda *

We should definitely document this better.

--spiff
--spiff

**Comment by jtran56** [comment]
Filed as internal issue #USD-4897.

**Comment by c64kernal** [comment]
Hey @jcowles , we're going to close this out based on @spiffmon comment.  Let us know if you still run into it in dev.
-George & Spiff

**Comment by jcowles** [comment]
Thanks guys!
