### ISSUE TITLE
Can not seem normal mapping effect in preview surface material

### ISSUE THREAD

**Issue by JoTiger** [PixarAnimationStudios/USD#701]
### Description of Issue
Normal mapping seems broken in Preview Surface material
### Steps to Reproduce
1. download retrotv.usdz from https://developer.apple.com/arkit/gallery/
2. open it with usdview, can not seem any bump or dent brought from normal mapping
3. change `Neye` https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usdImaging/lib/usdShaders/shaders/previewSurface.glslfx#L83 to `normal`, rebuild and reopen usdview. Now it looks like the normal mapping kicking in (though I have not checked that is the proper way to bring normal sampling into lighting). Current code seems just omit the normal sampling from texture.
### System Information (OS, Hardware)
Windows, GeForce 1070
### Package Versions
0.18.11

**Comment by spiffmon** [comment]
Hi @JoTiger ,
   Sorry, we haven't really documented which features of UsdPreviewSurface
we haven't yet implemented for our hdStream GL renderer.  There isn't yet
any support for normal mapping, because it requires a tangent space, which
we are not yet setup to support, and since we do more displacement than
normal mapping, it hasn't been at the top of the priority list.
Nevertheless, we do plan to eventually support it.  Firstly, within the
next year, we'll augment the definition of UsdPreviewSurface so that you
can connect *tangent* and *binormal* primvars, to supply a "baked" tangent
space.

Eventually we'll support an automatically computed tangent space, though
there's some internal debate about whether that should follow the game
industry and use Mikktspace, or whether to use OpenSubdiv to compute the
tangent space.

--spiff

**Comment by JoTiger** [comment]
@spiffmon Thanks for clarifying that.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4929.
