### ISSUE TITLE
No module named pixar.UsdMaya 

### ISSUE THREAD

**Issue by natwales** [PixarAnimationStudios/USD#722]
### Description of Issue
When trying to install pxrUSD.bundle from within the plugin manager in Maya 2017 (also 2018) I get an error:

`# Error: file: /Applications/Autodesk/maya2017/Maya.app/Contents/scripts/others/pluginWin.mel line 767: ImportError: file <maya console> line 4: No module named pixar.UsdMaya # `

When I try to use the plugin to export selection as USD I get another error:

`// Error: line 0: Cannot find procedure "usdTranslatorExport". // `

### Steps to Reproduce
1. checkout build v18.11
2. add environment variables as described. Confirmed all are correct, specifically, PYTHONPATH
`export PYTHONPATH="$PYTHONPATH:/usr/local/USD/lib/python/"`
3. open python 2.7 terminal from anaconda, and confirm environment variables with printenv
4. run python USD/build_scripts/build_usd.py /usr/local/USD --maya --maya-location /Applications/Autodesk/maya2017/Maya.app/Contents
5. launch Maya 2017 and attempt to install pxrUsdTranslators.bundle and then pxrUSD.bundle from  /usr/local/USD/third_party/maya/plugin

### System Information (OS, Hardware)
Mac OS High Sierra 10.13.6
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB

### Package Versions
v18.11

**Comment by natwales** [comment]
A source of confusion for me appears to have been where to add environment variables described on [this page](https://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html).

I had been adding those to my .bash_profile. However, I read about Maya.env and have tried defining those variables there instead. My errors go away in Maya as soon as I include the PYTHONPATH environment variable. However, Maya also crashes instantly with a EXC_CRASH (SIGABRT) exception.

**Comment by jtran56** [comment]
Field as internal issue #USD-4975.

**Comment by spiffmon** [comment]
Hi,
  The "pixar.Maya" path only kicks in when the normal "from pxr import UsdMaya" fails, and was due to some contortions we had to do for our internal build system.  @mattyjams has done work recently in the build system to eliminate the need for it, so it should be gone in the next github release.

   That leaves you back in the space of "USD build problems with Maya on OSX" which is a fertile delta :-)  Possibly the most likely one causing the crash is having our plugin pointing at the wrong python (it needs to be Maya's).  There are threads on the usd-interest forum where other folks have shared their experiences.

Cheers,
--spiff
