### ISSUE TITLE
Assertion hit in Hd_SortedIds::Remove() in VS2015 ("vector iterators incompatible")

### ISSUE THREAD

**Issue by christianaguilera-foundry** [PixarAnimationStudios/USD#731]
### Description of Issue
It seems that VS2015 does not like it when iterators are used after invalidation. In `Hd_SortedIds::Remove(const SdfPath&)`, the distance between two iterators is being calculated, but one of the iterators has already been invalidated. An assertion is hit if built in debug: _"vector iterators incompatible"_.

### Steps to Reproduce
- Build USD 18.11 with VS2015 in debug.
- Write a simple program.
- Add an element to a **Hd_SortedIds** vector with `Hd_SortedIds::Insert(const SdfPath&)`.
- Remove the element with `Hd_SortedIds::Insert(const SdfPath&)`.
- An assertion will be hit when recalculating `_sortedCount`.

### Potential fix
Calculate the value of `_sortedCount` before popping the item from the vector (which will invalidate the iterator).

```
index 0c55be58..a5088fb3 100644
@@ -92,6 +92,9 @@ Hd_SortedIds::Remove(const SdfPath &id)
 
     if (idToRemove != _ids.end()) {
         if (*idToRemove == id) {
+            const auto idxToRemove =
+                static_cast<size_t>(idToRemove - _ids.begin());
+
             SdfPathVector::iterator lastElement = _ids.end();
             --lastElement;
 
@@ -103,10 +106,7 @@ Hd_SortedIds::Remove(const SdfPath &id)
             // the list is now only sorted up to the place where the element
             // was removed.
 
-
-            _sortedCount = std::min(_sortedCount,
-                                    static_cast<size_t>(
-                                              (idToRemove - _ids.begin())));
+            _sortedCount = std::min(_sortedCount, idxToRemove);
         }
     }
 }
```

_NOTE: Only tested against USD 18.11, but should work as well for USD 19.01._

**Comment by christianaguilera-foundry** [comment]
Just noticed that in USD 19.01, there is now a second place where the invalidated iterator is used:

`_afterLastDeletePoint = idToRemove - _ids.begin();`

Introduced in https://github.com/PixarAnimationStudios/USD/commit/f9641764f307932ff91596e2197713a6001e52c3

**Comment by spitzak** [comment]
If the list was sorted then the swapped-in element is still sorted and the
sorted count is one larger than you are using.

I think this is correct:
   if (_sortedCount > _ids.size()) // greater as one element has been
deleted
       _sortedCount = idxToRemove+1;
   else if (_sortedCount > idxToRemove)
       _sortedCount = idxToRemove;

**Comment by spitzak** [comment]
Because you are using _sortedCount==size() rather than _sortedCount>=size()
to test if it is sorted, this needs to be fixed if the last item is deleted:

   if (_sortedCount > _ids.size() && idxToRemove < _ids.size())
       _sortedCount = idxToRemove+1;
   else if (_sortedCount > idxToRemove)
       _sortedCount = idxToRemove;

**Comment by usmanredsoft** [comment]
Kindly upload Pixar USD maya Xcode project source?

**Comment by jtran56** [comment]
Filed as internal issue #USD-4998.

**Comment by MWDD** [comment]
Hi,

  Firstly, thanks for filling this bug.

  I was not able to repro this bug as I don't have a debug windows build available at the moment and I wasn't able to reproduce it with iterator debug level 1 on a release build.   Gcc's iterator debugging was also not picking up the error.

  So going by code inspection, the code is access an invalidated iterator if the id to be removed was the the last element when computing sortedCount.

  I don't think _afterLastDeletePoint should be an issue as that is set inside the check for the last element and std::vector::pop_back() is supposed to only invalidate the last element and end() iterators.  However, as I haven't been able to confirm visual studio is able to detect and make this distinction.

  Therefore, my proposed patch for this issue is to move the update of sortedCount into the conditional testing to see if the last item in the list is removed.  The proposed change is below.  I haven't run this through the complete test suite yet and it's hasn't been peer reviewed, but I would love to get some feedback on whether this change fixes the issue on windows or not.

```
@@ -150,19 +150,25 @@
                 _ids.pop_back();
                 _afterLastDeletePoint = idToRemove - _ids.begin();
                 ++_afterLastDeletePoint;
+
+                // As we've moved an element from the end into the middle
+                // the list is now only sorted up to the place where the element
+                // was removed.
+
+                _sortedCount = std::min(_sortedCount,
+                                        static_cast<size_t>(
+                                                  (idToRemove - _ids.begin())));
             } else {
                 _ids.pop_back();
                 _afterLastDeletePoint = INVALID_DELETE_POINT;
+
+                // As we've removed an element from the end of the list
+                // the list remains in the same sort state, so
+                // trim the length if necessary.
+                // Note: Can't use the idToRemove iterator as that has
+                // been invalidated.
+                _sortedCount = std::min(_sortedCount, _ids.size());
             }
-
-            // As we've moved an element from the end into the middle
-            // the list is now only sorted up to the place where the element
-            // was removed.
-
-
-            _sortedCount = std::min(_sortedCount,
-                                    static_cast<size_t>(
-                                              (idToRemove - _ids.begin())));
         }
     }
 }

```
  Thanks,
MWDD
