### ISSUE TITLE
[usdMaya] representation unloaded after re-opening scene

### ISSUE THREAD

**Issue by mrharris** [PixarAnimationStudios/USD#778]
### Description of Issue
If I set a usdReferenceAssembly to a certain scene assembly representation (eg Playback or Full or Cards...) and save and reopen the scene, all of the usd nodes are reset to unloaded, rather than what was specified in the maya scene

### Steps to Reproduce
0. open maya
1. create usd node
2. set filepath to a usd file
3. set playback representation
4. save and reopen maya file
5. notice that playback representation is no longer active

### System Information (OS, Hardware)
centos 7

### Package Versions
usd-19.01

**Comment by spiffmon** [comment]
Hi @mrharris - this is intentional behavior, though admittedly not optimal.  The problem is that Maya considers assembly-state such as load/not-load and representation as scene-data, rather than user state.  In our workflows, we do not want the next person to load a particular Maya file to be burdened with the state of the previous user's, especially since the assemblies are there to solve a scalability problem, and you could get into a state where the file becomes difficult or unwieldy to load.

So we opted to make assemblies unloaded by default, and have deployed, internally, outliner context-menu commands that make it easy to recursively load assemblies to a particular representation.  It would take some work to factor those commands to be useful outside the studio, and given the popularity of the AL_UsdMaya plugin, we haven't considered it worth the effort.

**Comment by mrharris** [comment]
Thanks @spiffmon I suspected it was intentional but didn't find the motivation described anywhere. It looks like the representation state is recorded on the proxy node so we can look into doing something ourselves to restore it after a scene open
