### ISSUE TITLE
ArResolver: Environment variable to specify the resolver name

### ISSUE THREAD

**Issue by frenchdog** [PixarAnimationStudios/USD#831]
## Feature request
We need a way to set the preferred resolver using an environment variable.

If a DCCs is shipped with its own USD resolver, it could potentially block any other resolver to be loaded first if its name is not the first one.

For example, if the DCC Resolver name is "A" and our custom one is "B" then the only way to get our resolver used in the DCC is by calling `ArSetPreferredResolver("B")` from the DCC.
This will require some additional setup in the DCC launcher (assuming such DCC provide a python hook at startup) or some recompilation of the DCC USD plugin...

Instead, we would like to be able to set a variable PXR_AR_PREFFERED_RESOLVER="B" in the environment used to launch the DCC. Such variable would be picked by the ArResolver to set its prefered resolver.

**Comment by spiffmon** [comment]
Hi @frenchdog , 
   In working with SideFx, we uncovered this _specifically DCC_ problem, and developed a mechanism that allows DCC's to create an "uber resolver" that delegates to what would otherwise be "the" resolver for anything the DCC doesn't need to handle itself.  So far, it seems to be working, and doesn't open up quite as much potential for non-determinism as adding an env-var to pick from among multiple choices would.

The primary enhancements to allow this went [in this commit](https://github.com/PixarAnimationStudios/USD/commit/f2e063f1fda182fba2e862ced92f3417615afc23#diff-b8989c3ae50ca16c04a5536b657a69e4).  I reckon if you are testing Solaris you should be able to find where it gets used.

Going to close this for now, but please reopen if the existing mechanism doesn't meet your needs.
Thanks,
--spiff

**Comment by frenchdog** [comment]
Awesome! 
The DCC I was talking about was Houdini (Solaris) actually :). 
We are going to take a look, thanks!
