### ISSUE TITLE
Material update fails in Hydra when changing references or variants

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#978]
### Description of Issue
Edits to a stage which cause a material prim to be removed and replaced by different material prim in the same location do not update the material in Hydra. The render delegate is told to delete the material prim, but not told to re-create the new prim (because absolutely nothing about the prim using the material has changed, and materials are only populated when the rprim or the material binding changes).

This can be demonstrated in the case of replacing one referenced file with another, and when changing a variant selection.

### Steps to Reproduce
1. In the attached zip file, open sphere.usda into usdview.
[matupdatebug.zip](https://github.com/PixarAnimationStudios/USD/files/3640484/matupdatebug.zip)
2. In the interpreter window, run:
r = usdviewApi.stage.GetPrimAtPath('/reference1').GetReferences()
newref = Sdf.Reference('./mat2.usda', '/materials')
r.SetReferences([newref])
3. The sphere should turn blue, as the red material has been replaced by a red one. It does not. It remains red.
4. Open spherevariants.usda in usdview.
5. Change the variant selection on /mat from materiallibrary1 to materiallibrary2. This should also change the sphere from red to blue, but it does not.

### Package Versions
Built from dev branch on Sept 19, commit 980cc576775e8cae31f6473c243b2cfafdb5fc59.

**Comment by jtran56** [comment]
Filed as internal issue #USD-5580.

**Comment by sirpalee** [comment]
We got a very similar crash report with the Arnold render delegate, and I suspect it's the same issue. Attaching an example file with variants affecting an Arnold shader: [variant_crash.zip](https://github.com/PixarAnimationStudios/USD/files/6180765/variant_crash.zip).

arnold_vari_hang_modified.usda, where the variant is on the material, changing the variant will cause the following:
- Calling HdRenderDelegate::DestroySPrim on the material
- Calling HdRenderDelegate::CreateSPrim to create a new material (and syncing the material)
- Calling HdMesh::Sync to let the polymesh know the material id has changed

arnold_vari_hang.usda, where the variant is on the material, changing the variant will cause the following: 
- Calling HdRenderDelegate::DestroySPrim on the material
- Arnold crashes because the material has been destroyed (and thus Arnold nodes deleted)

The issue was replicated using 21.02 and #6be11aafc203cc97ffca3e934b92c9a497b5d103 on CentOS 7.

**Comment by c64kernal** [comment]
Closing, this particular issue was fixed with https://github.com/PixarAnimationStudios/USD/commit/b88813000b9fe42453b8eee19c15e373d3955e9e

More discussion here: https://groups.google.com/g/usd-interest/c/tl31uOY3Hh8 -- @sirpalee will file new issue for other case.
